export interface EmojiCategory {
	id: string;
	icon: string;
	label: string;
	emojis: string[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
	{
		id: "smileys",
		icon: "😀",
		label: "スマイリー",
		emojis: [
			// Face-Smiling
			"😀",
			"😃",
			"😄",
			"😁",
			"😆",
			"😅",
			"🤣",
			"😂",
			"🙂",
			"🙃",
			"🫠",
			"😉",
			"😊",
			"😇",
			// Face-Affection
			"🥰",
			"😍",
			"🤩",
			"😘",
			"😗",
			"☺️",
			"😚",
			"😙",
			"🥲",
			// Face-Tongue
			"😋",
			"😛",
			"😜",
			"🤪",
			"😝",
			"🤑",
			// Face-Hand
			"🤗",
			"🤭",
			"🫢",
			"🫣",
			"🤫",
			"🤔",
			"🫡",
			// Face-Neutral / Skeptical
			"🤐",
			"🤨",
			"😐",
			"😑",
			"😶",
			"🫥",
			"😶‍🌫️",
			"😏",
			"😒",
			"🙄",
			"😬",
			"😮‍💨",
			"🤥",
			// Face-Sleepy
			"😌",
			"😔",
			"😪",
			"🤤",
			"😴",
			// Face-Unwell
			"😷",
			"🤒",
			"🤕",
			"🤢",
			"🤮",
			"🥵",
			"🥶",
			"🥴",
			"😵",
			"😵‍💫",
			"🤯",
			// Face-Hat
			"🤠",
			"🥳",
			"🥸",
			// Face-Glasses
			"😎",
			"🤓",
			"🧐",
			// Face-Concerned
			"😕",
			"🫤",
			"😟",
			"🙁",
			"☹️",
			"😮",
			"😯",
			"😲",
			"😳",
			"🥺",
			"🥹",
			"😦",
			"😧",
			"😨",
			"😰",
			"😥",
			"😢",
			"😭",
			"😱",
			"😖",
			"😣",
			"😞",
			"😓",
			"😩",
			"😫",
			"🥱",
			// Face-Negative
			"😤",
			"😡",
			"😠",
			"🤬",
			// Face-Costume
			"😈",
			"👿",
			"💀",
			"☠️",
			"💩",
			"🤡",
			"👹",
			"👺",
			"👻",
			"👽",
			"👾",
			"🤖",
			// Cat-Face
			"😺",
			"😸",
			"😹",
			"😻",
			"😼",
			"😽",
			"🙀",
			"😿",
			"😾",
			// Monkey-Face
			"🙈",
			"🙉",
			"🙊",
			// Heart (emotion)
			"💌",
			"💘",
			"💝",
			"💖",
			"💗",
			"💓",
			"💞",
			"💕",
			"💟",
			"❣️",
			"💔",
			"❤️‍🔥",
			"❤️‍🩹",
			// Emotion
			"💋",
			"💯",
			"💢",
			"💥",
			"💫",
			"💦",
			"💨",
			"💤",
			"⚡",
			"🔥",
			"🕳️",
			"💬",
			"👁️‍🗨️",
			"🗨️",
			"🗯️",
			"💭",
		],
	},
	{
		id: "people",
		icon: "👋",
		label: "人と体",
		emojis: [
			// Hand-Fingers-Open
			"👋",
			"🤚",
			"🖐️",
			"✋",
			"🖖",
			"🫱",
			"🫲",
			"🫳",
			"🫴",
			// Hand-Fingers-Partial
			"👌",
			"🤌",
			"🤏",
			"✌️",
			"🤞",
			"🫰",
			"🤟",
			"🤘",
			"🤙",
			// Hand-Single-Finger
			"👈",
			"👉",
			"👆",
			"🖕",
			"👇",
			"☝️",
			"🫵",
			// Hand-Fingers-Closed
			"👍",
			"👎",
			"✊",
			"👊",
			"🤛",
			"🤜",
			// Hands
			"👏",
			"🙌",
			"🫶",
			"👐",
			"🤲",
			"🤝",
			"🙏",
			// Hand-Prop
			"✍️",
			"💅",
			"🤳",
			// Body-Parts
			"💪",
			"🦾",
			"🦿",
			"🦵",
			"🦶",
			"👂",
			"🦻",
			"👃",
			"🧠",
			"🫀",
			"🫁",
			"🦷",
			"🦴",
			"👀",
			"👁️",
			"👅",
			"👄",
			"🫦",
			// Person
			"👶",
			"🧒",
			"👦",
			"👧",
			"🧑",
			"👱",
			"👨",
			"🧔",
			"👩",
			"🧓",
			"👴",
			"👵",
			// Person-Gesture
			"🙍",
			"🙎",
			"🙅",
			"🙆",
			"💁",
			"🙋",
			"🧏",
			"🙇",
			"🤦",
			"🤷",
			// Person-Role
			"👮",
			"🕵️",
			"💂",
			"🥷",
			"👷",
			"🫅",
			"🤴",
			"👸",
			"👳",
			"👲",
			"🧕",
			"🤵",
			"👰",
			"🤰",
			"🫃",
			"🫄",
			"🤱",
			// Person-Fantasy
			"👼",
			"🎅",
			"🤶",
			"🦸",
			"🦹",
			"🧙",
			"🧚",
			"🧛",
			"🧜",
			"🧝",
			"🧞",
			"🧟",
			// Person-Activity
			"💆",
			"💇",
			"🚶",
			"🧍",
			"🧎",
			"🏃",
			"💃",
			"🕺",
			"🕴️",
			// Person-Sport
			"👯",
			"🧖",
			"🧗",
			"🤸",
			"🏌️",
			"🏇",
			"⛷️",
			"🏂",
			"🏋️",
			"🤼",
			"🤽",
			"🤾",
			"🤺",
			"⛹️",
			"🏄",
			"🚣",
			"🧘",
			"🏊",
			"🚴",
			"🚵",
			// Person-Resting
			"🛀",
			"🛌",
			// Family
			"👭",
			"👫",
			"👬",
			"💏",
			"💑",
			"👪",
			// Person-Symbol
			"🗣️",
			"👤",
			"👥",
			"🫂",
			// Body other
			"👣",
		],
	},
	{
		id: "animals",
		icon: "🐱",
		label: "動物と自然",
		emojis: [
			// Animal-Mammal
			"🐶",
			"🐕",
			"🦮",
			"🐕‍🦺",
			"🐩",
			"🐺",
			"🦊",
			"🦝",
			"🐱",
			"🐈",
			"🐈‍⬛",
			"🦁",
			"🐯",
			"🐅",
			"🐆",
			"🐴",
			"🫎",
			"🫏",
			"🐎",
			"🦄",
			"🦓",
			"🦌",
			"🦬",
			"🐮",
			"🐂",
			"🐃",
			"🐄",
			"🐷",
			"🐖",
			"🐗",
			"🐽",
			"🐏",
			"🐑",
			"🐐",
			"🐪",
			"🐫",
			"🦙",
			"🦒",
			"🐘",
			"🦣",
			"🦏",
			"🦛",
			"🐭",
			"🐁",
			"🐀",
			"🐹",
			"🐰",
			"🐇",
			"🐿️",
			"🦫",
			"🦔",
			"🦇",
			"🐻",
			"🐻‍❄️",
			"🐨",
			"🐼",
			"🦥",
			"🦦",
			"🦨",
			"🦘",
			"🦡",
			"🐾",
			// Animal-Bird
			"🐔",
			"🐓",
			"🐣",
			"🐤",
			"🐥",
			"🐦",
			"🐧",
			"🕊️",
			"🦅",
			"🦆",
			"🦢",
			"🦉",
			"🦤",
			"🪶",
			"🦩",
			"🦚",
			"🦜",
			// Animal-Amphibian
			"🐸",
			// Animal-Reptile
			"🐊",
			"🐢",
			"🦎",
			"🐍",
			"🐲",
			"🐉",
			"🦕",
			"🦖",
			// Animal-Marine
			"🐳",
			"🐋",
			"🐬",
			"🦭",
			"🐟",
			"🐠",
			"🐡",
			"🦈",
			"🐙",
			"🐚",
			"🪸",
			"🪼",
			// Animal-Bug
			"🐌",
			"🦋",
			"🐛",
			"🐜",
			"🐝",
			"🪲",
			"🐞",
			"🦗",
			"🪳",
			"🕷️",
			"🕸️",
			"🦂",
			"🦟",
			"🪰",
			"🪱",
			// Plant-Flower
			"💐",
			"🌸",
			"💮",
			"🪷",
			"🏵️",
			"🌹",
			"🥀",
			"🌺",
			"🌻",
			"🌼",
			"🌷",
			// Plant-Other
			"🪻",
			"🌱",
			"🪴",
			"🌲",
			"🌳",
			"🌴",
			"🌵",
			"🌾",
			"🌿",
			"☘️",
			"🍀",
			"🍁",
			"🍂",
			"🍃",
			"🪹",
			"🪺",
			"🍄",
			// Sky & Weather
			"☀️",
			"🌤️",
			"⛅",
			"🌥️",
			"☁️",
			"🌦️",
			"🌧️",
			"⛈️",
			"🌩️",
			"🌨️",
			"❄️",
			"☃️",
			"⛄",
			"🌬️",
			"🌪️",
			"🌫️",
			"🌈",
			"☔",
			"💧",
			"🌊",
		],
	},
	{
		id: "food",
		icon: "🍎",
		label: "食べ物",
		emojis: [
			// Food-Fruit
			"🍇",
			"🍈",
			"🍉",
			"🍊",
			"🍋",
			"🍌",
			"🍍",
			"🥭",
			"🍎",
			"🍏",
			"🍐",
			"🍑",
			"🍒",
			"🍓",
			"🫐",
			"🥝",
			"🍅",
			"🫒",
			"🥥",
			// Food-Vegetable
			"🥑",
			"🍆",
			"🥔",
			"🥕",
			"🌽",
			"🌶️",
			"🫑",
			"🥒",
			"🥬",
			"🥦",
			"🧄",
			"🧅",
			"🥜",
			"🫘",
			"🌰",
			// Food-Prepared
			"🍞",
			"🥐",
			"🥖",
			"🫓",
			"🥨",
			"🥯",
			"🥞",
			"🧇",
			"🧀",
			"🍖",
			"🍗",
			"🥩",
			"🥓",
			"🍔",
			"🍟",
			"🍕",
			"🌭",
			"🥪",
			"🌮",
			"🌯",
			"🫔",
			"🥙",
			"🧆",
			"🥚",
			"🍳",
			"🥘",
			"🍲",
			"🫕",
			"🥣",
			"🥗",
			"🍿",
			"🧈",
			"🧂",
			"🥫",
			// Food-Asian
			"🍱",
			"🍘",
			"🍙",
			"🍚",
			"🍛",
			"🍜",
			"🍝",
			"🍠",
			"🍢",
			"🍣",
			"🍤",
			"🍥",
			"🥮",
			"🍡",
			"🥟",
			"🥠",
			"🥡",
			// Food-Marine
			"🦀",
			"🦞",
			"🦐",
			"🦑",
			"🦪",
			// Food-Sweet
			"🍦",
			"🍧",
			"🍨",
			"🍩",
			"🍪",
			"🎂",
			"🍰",
			"🧁",
			"🥧",
			"🍫",
			"🍬",
			"🍭",
			"🍮",
			"🍯",
			// Drink
			"🍼",
			"🥛",
			"☕",
			"🫖",
			"🍵",
			"🍶",
			"🍾",
			"🍷",
			"🍸",
			"🍹",
			"🍺",
			"🍻",
			"🥂",
			"🥃",
			"🫗",
			"🥤",
			"🧋",
			"🧃",
			"🧉",
			"🧊",
			// Dishware
			"🥢",
			"🍽️",
			"🍴",
			"🥄",
			"🔪",
			"🫙",
			"🏺",
		],
	},
	{
		id: "activities",
		icon: "⚽",
		label: "アクティビティ",
		emojis: [
			// Event
			"🎃",
			"🎄",
			"🎆",
			"🎇",
			"🧨",
			"✨",
			"🎈",
			"🎉",
			"🎊",
			"🎋",
			"🎍",
			"🎎",
			"🎏",
			"🎐",
			"🎑",
			"🧧",
			"🎀",
			"🎁",
			"🎗️",
			"🎟️",
			"🎫",
			// Award-Medal
			"🎖️",
			"🏆",
			"🏅",
			"🥇",
			"🥈",
			"🥉",
			// Sport
			"⚽",
			"⚾",
			"🥎",
			"🏀",
			"🏐",
			"🏈",
			"🏉",
			"🎾",
			"🥏",
			"🎳",
			"🏏",
			"🏑",
			"🏒",
			"🥍",
			"🏓",
			"🏸",
			"🥊",
			"🥋",
			"🥅",
			"⛳",
			"⛸️",
			"🎣",
			"🤿",
			"🎽",
			"🎿",
			"🛷",
			"🥌",
			// Game
			"🎯",
			"🪀",
			"🪁",
			"🔫",
			"🎱",
			"🔮",
			"🪄",
			"🧿",
			"🪬",
			"🎮",
			"🕹️",
			"🎰",
			"🎲",
			"🧩",
			"🧸",
			"🪅",
			"🪩",
			"🪆",
			// Arts & Crafts
			"♠️",
			"♥️",
			"♦️",
			"♣️",
			"♟️",
			"🃏",
			"🀄",
			"🎭",
			"🖼️",
			"🎨",
			"🧵",
			"🪡",
			"🧶",
			"🪢",
		],
	},
	{
		id: "travel",
		icon: "🏠",
		label: "旅行と場所",
		emojis: [
			// Globe
			"🌍",
			"🌎",
			"🌏",
			"🌐",
			"🗺️",
			"🧭",
			// Geographic
			"🏔️",
			"⛰️",
			"🌋",
			"🗻",
			"🏕️",
			"🏖️",
			"🏜️",
			"🏝️",
			"🏞️",
			// Building
			"🏟️",
			"🏛️",
			"🏗️",
			"🧱",
			"🪨",
			"🪵",
			"🛖",
			"🏘️",
			"🏚️",
			"🏠",
			"🏡",
			"🏢",
			"🏣",
			"🏤",
			"🏥",
			"🏦",
			"🏨",
			"🏩",
			"🏪",
			"🏫",
			"🏬",
			"🏭",
			"🏯",
			"🏰",
			"💒",
			"🗼",
			"🗽",
			// Religious
			"⛪",
			"🕌",
			"🛕",
			"🕍",
			"⛩️",
			"🕋",
			// Other-Place
			"⛲",
			"⛺",
			"🌁",
			"🌃",
			"🏙️",
			"🌄",
			"🌅",
			"🌆",
			"🌇",
			"🌉",
			"🌌",
			// Transport-Ground
			"♨️",
			"🎠",
			"🛝",
			"🎡",
			"🎢",
			"💈",
			"🎪",
			"🚂",
			"🚃",
			"🚄",
			"🚅",
			"🚆",
			"🚇",
			"🚈",
			"🚉",
			"🚊",
			"🚝",
			"🚞",
			"🚋",
			"🚌",
			"🚍",
			"🚎",
			"🚐",
			"🚑",
			"🚒",
			"🚓",
			"🚔",
			"🚕",
			"🚖",
			"🚗",
			"🚘",
			"🚙",
			"🛻",
			"🚚",
			"🚛",
			"🚜",
			"🏎️",
			"🏍️",
			"🛵",
			"🦽",
			"🦼",
			"🛺",
			"🚲",
			"🛴",
			"🛹",
			"🛼",
			"🚏",
			"🛣️",
			"🛤️",
			"🛞",
			"⛽",
			"🚨",
			"🚥",
			"🚦",
			"🛑",
			"🚧",
			// Transport-Water
			"⚓",
			"🛟",
			"⛵",
			"🛶",
			"🚤",
			"🛳️",
			"⛴️",
			"🛥️",
			"🚢",
			// Transport-Air
			"✈️",
			"🛩️",
			"🛫",
			"🛬",
			"🪂",
			"💺",
			"🚁",
			"🚟",
			"🚠",
			"🚡",
			"🛸",
			"🚀",
			"🛰️",
			// Time
			"🕐",
			"🕑",
			"🕒",
			"🕓",
			"🕔",
			"🕕",
			"🕖",
			"🕗",
			"🕘",
			"🕙",
			"🕚",
			"🕛",
			"🕜",
			"🕝",
			"🕞",
			"🕟",
			"🕠",
			"🕡",
			"🕢",
			"🕣",
			"🕤",
			"🕥",
			"🕦",
			"🕧",
			// Sky & Weather (in travel context)
			"🌑",
			"🌒",
			"🌓",
			"🌔",
			"🌕",
			"🌖",
			"🌗",
			"🌘",
			"🌙",
			"🌚",
			"🌛",
			"🌜",
			"🌡️",
			"🌝",
			"🌞",
			"🪐",
			"⭐",
			"🌟",
		],
	},
	{
		id: "objects",
		icon: "💡",
		label: "オブジェクト",
		emojis: [
			// Clothing
			"👓",
			"🕶️",
			"🥽",
			"🥼",
			"🦺",
			"👔",
			"👕",
			"👖",
			"🧣",
			"🧤",
			"🧥",
			"🧦",
			"👗",
			"👘",
			"🥻",
			"🩱",
			"🩲",
			"🩳",
			"👙",
			"👚",
			"🪭",
			"👛",
			"👜",
			"👝",
			"🛍️",
			"🎒",
			"🩴",
			"👞",
			"👟",
			"🥾",
			"🥿",
			"👠",
			"👡",
			"🩰",
			"👢",
			"🪮",
			"👑",
			"👒",
			"🎩",
			"🎓",
			"🧢",
			"🪖",
			"⛑️",
			"📿",
			"💄",
			"💍",
			"💎",
			// Sound
			"🔇",
			"🔈",
			"🔉",
			"🔊",
			"📢",
			"📣",
			"📯",
			"🔔",
			"🔕",
			// Music
			"🎼",
			"🎵",
			"🎶",
			"🎙️",
			"🎚️",
			"🎛️",
			"🎤",
			"🎧",
			"📻",
			// Musical-Instrument
			"🎷",
			"🪗",
			"🎸",
			"🎹",
			"🎺",
			"🎻",
			"🪕",
			"🥁",
			"🪘",
			// Phone
			"📱",
			"📲",
			"☎️",
			"📞",
			"📟",
			"📠",
			// Computer
			"🔋",
			"🪫",
			"🔌",
			"💻",
			"🖥️",
			"🖨️",
			"⌨️",
			"🖱️",
			"🖲️",
			"💽",
			"💾",
			"💿",
			"📀",
			"🧮",
			// Light & Video
			"🎥",
			"🎞️",
			"📽️",
			"🎬",
			"📺",
			"📷",
			"📸",
			"📹",
			"📼",
			"🔍",
			"🔎",
			"🕯️",
			"💡",
			"🔦",
			"🏮",
			"🪔",
			// Book-Paper
			"📔",
			"📕",
			"📖",
			"📗",
			"📘",
			"📙",
			"📚",
			"📓",
			"📒",
			"📃",
			"📜",
			"📄",
			"📰",
			"🗞️",
			"📑",
			"🔖",
			"🏷️",
			// Money
			"💰",
			"🪙",
			"💴",
			"💵",
			"💶",
			"💷",
			"💸",
			"💳",
			"🧾",
			"💹",
			// Mail
			"✉️",
			"📧",
			"📨",
			"📩",
			"📤",
			"📥",
			"📦",
			"📫",
			"📪",
			"📬",
			"📭",
			"📮",
			"🗳️",
			// Writing
			"✏️",
			"✒️",
			"🖋️",
			"🖊️",
			"🖌️",
			"🖍️",
			"📝",
			// Office
			"💼",
			"📁",
			"📂",
			"🗂️",
			"📅",
			"📆",
			"🗒️",
			"🗓️",
			"📇",
			"📈",
			"📉",
			"📊",
			"📋",
			"📌",
			"📍",
			"📎",
			"🖇️",
			"📏",
			"📐",
			"✂️",
			"🗃️",
			"🗄️",
			"🗑️",
			// Lock
			"🔒",
			"🔓",
			"🔏",
			"🔐",
			"🔑",
			"🗝️",
			// Tool
			"🔨",
			"🪓",
			"⛏️",
			"⚒️",
			"🛠️",
			"🗡️",
			"⚔️",
			"💣",
			"🪃",
			"🏹",
			"🛡️",
			"🪚",
			"🔧",
			"🪛",
			"🔩",
			"⚙️",
			"🗜️",
			"⚖️",
			"🦯",
			"🔗",
			"⛓️",
			"🪝",
			"🧰",
			"🧲",
			"🪜",
			// Science
			"⚗️",
			"🧪",
			"🧫",
			"🧬",
			"🔬",
			"🔭",
			"📡",
			// Medical
			"💉",
			"🩸",
			"💊",
			"🩹",
			"🩼",
			"🩺",
			"🩻",
			// Household
			"🚪",
			"🛗",
			"🪞",
			"🪟",
			"🛏️",
			"🛋️",
			"🪑",
			"🚽",
			"🪠",
			"🚿",
			"🛁",
			"🪤",
			"🪒",
			"🧴",
			"🧷",
			"🧹",
			"🧺",
			"🧻",
			"🪣",
			"🧼",
			"🫧",
			"🪥",
			"🧽",
			"🧯",
			"🛒",
			// Other-Object
			"⏰",
			"⏱️",
			"⏲️",
			"🕰️",
			"⌛",
			"⏳",
			"🚬",
			"⚰️",
			"🪦",
			"⚱️",
			"🗿",
			"🪧",
			"🪪",
		],
	},
	{
		id: "symbols",
		icon: "❤️",
		label: "記号",
		emojis: [
			// Hearts (colored - emotion hearts are in smileys)
			"❤️",
			"🧡",
			"💛",
			"💚",
			"💙",
			"💜",
			"🖤",
			"🤍",
			"🤎",
			// Geometric
			"🔴",
			"🟠",
			"🟡",
			"🟢",
			"🔵",
			"🟣",
			"🟤",
			"⚫",
			"⚪",
			"🟥",
			"🟧",
			"🟨",
			"🟩",
			"🟦",
			"🟪",
			"🟫",
			"⬛",
			"⬜",
			"◼️",
			"◻️",
			"◾",
			"◽",
			"▪️",
			"▫️",
			"🔶",
			"🔷",
			"🔸",
			"🔹",
			"🔺",
			"🔻",
			"💠",
			"🔘",
			"🔳",
			"🔲",
			// Zodiac
			"♈",
			"♉",
			"♊",
			"♋",
			"♌",
			"♍",
			"♎",
			"♏",
			"♐",
			"♑",
			"♒",
			"♓",
			"⛎",
			// AV-Symbol
			"🔀",
			"🔁",
			"🔂",
			"▶️",
			"⏩",
			"⏭️",
			"⏯️",
			"◀️",
			"⏪",
			"⏮️",
			"🔼",
			"⏫",
			"🔽",
			"⏬",
			"⏸️",
			"⏹️",
			"⏺️",
			"⏏️",
			"🎦",
			"🔅",
			"🔆",
			"📶",
			"🛜",
			"📳",
			"📴",
			// Gender & Medical
			"♀️",
			"♂️",
			"⚧️",
			// Math
			"✖️",
			"➕",
			"➖",
			"➗",
			"🟰",
			"♾️",
			// Punctuation
			"‼️",
			"⁉️",
			"❓",
			"❔",
			"❕",
			"❗",
			// Currency
			"💱",
			"💲",
			// Other-Symbol
			"⚕️",
			"♻️",
			"⚜️",
			"🔱",
			"📛",
			"🔰",
			"⭕",
			"✅",
			"☑️",
			"✔️",
			"❌",
			"❎",
			"➰",
			"➿",
			"〽️",
			"✳️",
			"✴️",
			"❇️",
			"©️",
			"®️",
			"™️",
			// Keycap
			"#️⃣",
			"*️⃣",
			"0️⃣",
			"1️⃣",
			"2️⃣",
			"3️⃣",
			"4️⃣",
			"5️⃣",
			"6️⃣",
			"7️⃣",
			"8️⃣",
			"9️⃣",
			"🔟",
			// Alphabet
			"🔠",
			"🔡",
			"🔢",
			"🔣",
			"🔤",
			"🅰️",
			"🆎",
			"🅱️",
			"🆑",
			"🆒",
			"🆓",
			"ℹ️",
			"🆔",
			"Ⓜ️",
			"🆕",
			"🆖",
			"🅾️",
			"🆗",
			"🅿️",
			"🆘",
			"🆙",
			"🆚",
			"🈁",
			"🈂️",
			"🈷️",
			"🈶",
			"🈯",
			"🉐",
			"🈹",
			"🈚",
			"🈲",
			"🉑",
			"🈸",
			"🈴",
			"🈳",
			"㊗️",
			"㊙️",
			"🈺",
			"🈵",
			// Arrow
			"⬆️",
			"↗️",
			"➡️",
			"↘️",
			"⬇️",
			"↙️",
			"⬅️",
			"↖️",
			"↕️",
			"↔️",
			"↩️",
			"↪️",
			"⤴️",
			"⤵️",
			"🔃",
			"🔄",
			// Religion
			"🛐",
			"⚛️",
			"🕉️",
			"✡️",
			"☸️",
			"☯️",
			"✝️",
			"☦️",
			"☪️",
			"☮️",
			"🕎",
			"🔯",
			// Warning
			"⚠️",
			"🚫",
			"🚳",
			"🚭",
			"🚯",
			"🚱",
			"🚷",
			"📵",
			"🔞",
			"☢️",
			"☣️",
			// Information
			"🏧",
			"🚮",
			"🚰",
			"♿",
			"🚹",
			"🚺",
			"🚻",
			"🚼",
			"🚾",
			"🛂",
			"🛃",
			"🛄",
			"🛅",
			// Flags (non-country)
			"🏁",
			"🚩",
			"🎌",
			"🏳️",
			"🏴",
			"🏳️‍🌈",
			"🏳️‍⚧️",
			"🏴‍☠️",
		],
	},
];

const EMOJI_KEYWORDS: Record<string, string> = {
	// ==================== SMILEYS ====================
	"😀": "grinning face smile happy 笑顔 にこにこ",
	"😃": "grinning face big eyes smile open 笑顔 嬉しい",
	"😄": "grinning face smiling eyes laugh happy 笑い 嬉しい",
	"😁": "beaming face smiling eyes grin teeth 笑顔 歯",
	"😆": "grinning squinting face laughing 大笑い",
	"😅": "grinning face sweat drop nervous 苦笑い 汗",
	"🤣": "rolling on the floor laughing rofl 大爆笑",
	"😂": "face with tears of joy crying laughing 嬉し泣き 笑い泣き",
	"🙂": "slightly smiling face 微笑み",
	"🙃": "upside-down face silly sarcasm 逆さ顔",
	"🫠": "melting face hot disappear 溶ける",
	"😉": "winking face ウインク",
	"😊": "smiling face smiling eyes blush warm 照れ にこにこ",
	"😇": "smiling face halo angel innocent 天使 聖人",
	"🥰": "smiling face hearts love adore 愛 大好き",
	"😍": "smiling face heart-eyes love crush 目がハート 好き",
	"🤩": "star-struck excited amazed 興奮 スター",
	"😘": "face blowing kiss love 投げキス キス",
	"😗": "kissing face pucker キス",
	"☺️": "smiling face relaxed warm ほっこり 微笑み",
	"😚": "kissing face closed eyes kiss キス",
	"😙": "kissing face smiling eyes kiss キス",
	"🥲": "smiling face tear sad happy 嬉し涙 切ない",
	"😋": "face savoring food yummy delicious 美味しい おいしい",
	"😛": "face with tongue stuck out playful 舌",
	"😜": "winking face tongue crazy ふざけ あっかんべー",
	"🤪": "zany face crazy wild goofy おどけ",
	"😝": "squinting face tongue 舌出し",
	"🤑": "money-mouth face dollar rich 金 お金",
	"🤗": "smiling face open hands hug ハグ 抱擁",
	"🤭": "face with hand over mouth giggle oops 手で口を覆う くすくす",
	"🫢": "face with open eyes hand over mouth surprise shock 驚き",
	"🫣": "face with peeking eye shy 覗く 恥ずかしい",
	"🤫": "shushing face quiet secret 秘密 静かに",
	"🤔": "thinking face hmm wonder 考え中 うーん",
	"🫡": "saluting face respect salute 敬礼",
	"🤐": "zipper-mouth face secret shut 口チャック",
	"🤨": "face raised eyebrow skeptical 疑い 片眉",
	"😐": "neutral face expressionless 無表情",
	"😑": "expressionless face blank 無表情 真顔",
	"😶": "face without mouth silent speechless 沈黙",
	"🫥": "dotted line face invisible hidden 透明 見えない",
	"😶‍🌫️": "face in clouds foggy confused 雲 モヤ",
	"😏": "smirking face sly suggestive ニヤリ",
	"😒": "unamused face annoyed bored つまらない",
	"🙄": "face rolling eyes whatever やれやれ",
	"😬": "grimacing face awkward nervous 苦笑い しかめ",
	"😮‍💨": "face exhaling sigh relief ため息",
	"🤥": "lying face pinocchio nose 嘘つき ピノキオ",
	"😌": "relieved face peaceful calm 安心 穏やか",
	"😔": "pensive face sad thoughtful 悲しい 残念",
	"😪": "sleepy face tear tired 眠い 涙",
	"🤤": "drooling face hungry 涎 よだれ",
	"😴": "sleeping face zzz snore 睡眠 寝る",
	"😷": "face medical mask sick ill マスク 病気",
	"🤒": "face thermometer fever sick 体温計 熱",
	"🤕": "face head-bandage hurt injured 怪我 包帯",
	"🤢": "nauseated face sick green 吐き気 気持ち悪い",
	"🤮": "face vomiting throw up 嘔吐 吐く",
	"🥵": "hot face sweating overheated 暑い 熱い",
	"🥶": "cold face freezing frozen 寒い 凍える",
	"🥴": "woozy face dizzy drunk 酔い ふらふら",
	"😵": "face crossed-out eyes dizzy knocked 目が回る",
	"😵‍💫": "face spiral eyes dizzy confused 目が回る",
	"🤯": "exploding head mind blown shocked 衝撃 頭爆発",
	"🤠": "cowboy hat face western カウボーイ",
	"🥳": "partying face celebrate birthday パーティ お祝い",
	"🥸": "disguised face nose glasses 変装 眼鏡",
	"😎": "smiling face sunglasses cool かっこいい サングラス",
	"🤓": "nerd face glasses smart オタク メガネ 賢い",
	"🧐": "face monocle inspect examine 調査 モノクル",
	"😕": "confused face puzzled 困惑 わからない",
	"🫤": "face diagonal mouth unsure uncertain 微妙",
	"😟": "worried face concern anxious 心配 不安",
	"🙁": "slightly frowning face sad 少し悲しい",
	"☹️": "frowning face sad unhappy 悲しい 不幸",
	"😮": "face open mouth surprised wow 驚き 口開き",
	"😯": "hushed face stunned shocked びっくり",
	"😲": "astonished face amazed shocked 驚愕 びっくり",
	"😳": "flushed face embarrassed surprised 赤面 恥ずかしい",
	"🥺": "pleading face puppy eyes beg おねがい うるうる",
	"🥹": "face holding back tears emotional moved 感動 涙こらえる",
	"😦": "frowning face open mouth 口開き 困惑",
	"😧": "anguished face distressed 苦悩",
	"😨": "fearful face scared afraid 恐怖 怖い",
	"😰": "anxious face sweat worried 不安 冷や汗",
	"😥": "sad but relieved face disappointed 残念 安堵",
	"😢": "crying face tear sad 泣く 涙",
	"😭": "loudly crying face sob wail 号泣 大泣き",
	"😱": "face screaming fear horror 叫び 恐怖",
	"😖": "confounded face frustrated 困惑 挫折",
	"😣": "persevering face struggling 頑張り 辛抱",
	"😞": "disappointed face sad let down がっかり 失望",
	"😓": "downcast face sweat 汗 落胆",
	"😩": "weary face tired exhausted 疲れ うんざり",
	"😫": "tired face exhausted fed up 疲労 くたくた",
	"🥱": "yawning face bored sleepy あくび 退屈",
	"😤": "face steam from nose triumph angry 鼻息 怒り",
	"😡": "pouting face angry mad rage 激怒 怒り",
	"😠": "angry face mad grumpy 怒り 不機嫌",
	"🤬": "face symbols on mouth swearing cursing 罵り 悪態",
	"😈": "smiling face horns devil evil 悪魔 デビル",
	"👿": "angry face horns devil imp 怒り悪魔",
	"💀": "skull death dead ドクロ 骸骨 死",
	"☠️": "skull crossbones death danger ドクロ 危険",
	"💩": "pile of poo poop funny うんち 💩",
	"🤡": "clown face circus funny ピエロ 道化師",
	"👹": "ogre monster Japanese oni 鬼 おに",
	"👺": "goblin tengu Japanese 天狗 てんぐ",
	"👻": "ghost boo spooky Halloween おばけ 幽霊",
	"👽": "alien extraterrestrial UFO 宇宙人 エイリアン",
	"👾": "alien monster space invader ゲーム インベーダー",
	"🤖": "robot face bot machine ロボット",
	"😺": "grinning cat smile 猫 笑顔",
	"😸": "grinning cat smiling eyes 猫 にこにこ",
	"😹": "cat tears of joy laugh 猫 嬉し泣き",
	"😻": "smiling cat heart-eyes love 猫 目がハート",
	"😼": "cat wry smile smirk 猫 ニヤリ",
	"😽": "kissing cat love 猫 キス",
	"🙀": "weary cat shocked surprised 猫 驚き",
	"😿": "crying cat sad tear 猫 泣く",
	"😾": "pouting cat angry grumpy 猫 怒り",
	"🙈": "see-no-evil monkey 見ざる 猿",
	"🙉": "hear-no-evil monkey 聞かざる 猿",
	"🙊": "speak-no-evil monkey 言わざる 猿",
	"💌": "love letter envelope heart ラブレター 手紙",
	"💘": "heart with arrow cupid love キューピッド ハート矢",
	"💝": "heart with ribbon gift ハート リボン プレゼント",
	"💖": "sparkling heart shine love キラキラ ハート",
	"💗": "growing heart expanding love 大きくなるハート",
	"💓": "beating heart pulse love ドキドキ 鼓動",
	"💞": "revolving hearts love orbit 回転ハート",
	"💕": "two hearts love couple ダブルハート",
	"💟": "heart decoration ハートデコレーション",
	"❣️": "heart exclamation love ハート ビックリマーク",
	"💔": "broken heart sad breakup 失恋 ハートブレイク",
	"❤️‍🔥": "heart on fire passion burning 燃えるハート 情熱",
	"❤️‍🩹": "mending heart healing recovery 回復 癒し",
	"💋": "kiss mark lipstick キスマーク 口紅",
	"💯": "hundred points perfect score 百点 満点 完璧",
	"💢": "anger symbol mad 怒りマーク",
	"💥": "collision boom bang 爆発 衝突",
	"💫": "dizzy star shooting 目が回る 流れ星",
	"💦": "sweat droplets water splash 汗 水滴",
	"💨": "dashing away wind fast 風 ダッシュ 速い",
	"🕳️": "hole opening 穴",
	"💬": "speech balloon talk chat 吹き出し 会話",
	"👁️‍🗨️": "eye speech bubble witness 目 証人",
	"🗨️": "left speech bubble talk 吹き出し 左",
	"🗯️": "right anger bubble shout 怒り 吹き出し",
	"💭": "thought balloon thinking 思考 考え",

	// ==================== PEOPLE ====================
	"👋": "waving hand hello bye greeting 手を振る こんにちは さようなら",
	"🤚": "raised back of hand stop 手の甲",
	"🖐️": "hand with fingers splayed open 手 広げる",
	"✋": "raised hand stop high five ハイタッチ ストップ",
	"🖖": "vulcan salute spock バルカン スタートレック",
	"🫱": "rightwards hand 右手",
	"🫲": "leftwards hand 左手",
	"🫳": "palm down hand drop lower 手のひら 下",
	"🫴": "palm up hand offer receive 手のひら 上",
	"👌": "ok hand perfect good OKサイン 完璧",
	"🤌": "pinched fingers Italian つまむ イタリア",
	"🤏": "pinching hand small tiny 少し つまむ",
	"✌️": "victory hand peace sign ピース 勝利",
	"🤞": "crossed fingers luck hope 幸運 願い",
	"🫰": "hand with index finger and thumb crossed money love お金 ラブ",
	"🤟": "love-you gesture ILY sign 愛してる",
	"🤘": "sign of the horns rock metal ロック メタル",
	"🤙": "call me hand shaka phone 電話 シャカ",
	"👈": "backhand index pointing left 左 指差し",
	"👉": "backhand index pointing right 右 指差し",
	"👆": "backhand index pointing up 上 指差し",
	"🖕": "middle finger rude 中指",
	"👇": "backhand index pointing down 下 指差し",
	"☝️": "index pointing up one 人差し指 上",
	"🫵": "index pointing at the viewer you あなた 指差し",
	"👍": "thumbs up good approve like いいね 賛成 グッド",
	"👎": "thumbs down bad disapprove dislike 反対 ダメ",
	"✊": "raised fist power solidarity グー 拳 力",
	"👊": "oncoming fist punch bump パンチ グー",
	"🤛": "left-facing fist bump 左拳",
	"🤜": "right-facing fist bump 右拳",
	"👏": "clapping hands applause bravo 拍手 パチパチ",
	"🙌": "raising hands celebrate hooray 万歳 バンザイ",
	"🫶": "heart hands love gesture 手でハート",
	"👐": "open hands jazz 手のひら 広げる",
	"🤲": "palms up together receive pray 両手 受ける",
	"🤝": "handshake deal agree 握手 契約",
	"🙏": "folded hands pray please thanks お願い 祈り 感謝 ありがとう",
	"✍️": "writing hand pen 書く ペン",
	"💅": "nail polish manicure beauty ネイル マニキュア",
	"🤳": "selfie phone camera 自撮り セルフィー",
	"💪": "flexed biceps strong muscle 筋肉 力 強い",
	"🦾": "mechanical arm prosthetic robot 義手 ロボット腕",
	"🦿": "mechanical leg prosthetic 義足 ロボット脚",
	"🦵": "leg limb kick 脚 足 キック",
	"🦶": "foot toe kick 足 つま先",
	"👂": "ear hear listen 耳 聞く",
	"🦻": "ear hearing aid 補聴器 耳",
	"👃": "nose smell sniff 鼻 匂い",
	"🧠": "brain think smart mind 脳 頭脳 知性",
	"🫀": "anatomical heart organ 心臓 臓器",
	"🫁": "lungs breathe organ 肺 呼吸",
	"🦷": "tooth dental smile 歯 歯医者",
	"🦴": "bone skeleton 骨 スケルトン",
	"👀": "eyes look see watch 目 見る 視線",
	"👁️": "eye single see 目 単眼",
	"👅": "tongue lick taste 舌 味",
	"👄": "mouth lips talk 口 唇 話す",
	"🫦": "biting lip nervous flirt 唇を噛む 緊張",
	"👶": "baby infant child 赤ちゃん 乳児",
	"🧒": "child kid young 子供 こども",
	"👦": "boy young male 男の子 少年",
	"👧": "girl young female 女の子 少女",
	"🧑": "person adult 人 大人",
	"👱": "person blond hair blonde 金髪",
	"👨": "man male adult 男 男性",
	"🧔": "person beard facial hair ひげ 髭",
	"👩": "woman female adult 女 女性",
	"🧓": "older person elder senior 高齢者 お年寄り",
	"👴": "old man grandpa grandfather おじいさん 祖父",
	"👵": "old woman grandma grandmother おばあさん 祖母",
	"🙍": "person frowning sad 悲しむ人",
	"🙎": "person pouting angry 怒る人 ふくれる",
	"🙅": "person gesturing no deny 駄目 NG バツ",
	"🙆": "person gesturing ok yes OK 丸",
	"💁": "person tipping hand info information 案内 情報",
	"🙋": "person raising hand volunteer question 挙手 質問",
	"🧏": "deaf person hearing 聴覚障害",
	"🙇": "person bowing apologize sorry お辞儀 すみません",
	"🤦": "person facepalm disbelief やれやれ 呆れ",
	"🤷": "person shrugging unsure idk わからない 知らない",
	"👮": "police officer cop law 警察 おまわりさん",
	"🕵️": "detective spy investigate 探偵 スパイ",
	"💂": "guard royal British 衛兵 護衛",
	"🥷": "ninja stealth warrior 忍者 にんじゃ",
	"👷": "construction worker builder 工事 作業員",
	"🫅": "person with crown royal 王冠",
	"🤴": "prince royal male 王子",
	"👸": "princess royal female 姫 お姫様 プリンセス",
	"👳": "person wearing turban ターバン",
	"👲": "person with skullcap Chinese cap 帽子",
	"🧕": "woman with headscarf hijab ヒジャブ スカーフ",
	"🤵": "person in tuxedo formal groom タキシード フォーマル",
	"👰": "person with veil bride wedding ベール 花嫁",
	"🤰": "pregnant woman expecting baby 妊婦 妊娠",
	"🫃": "pregnant man 妊娠 男性",
	"🫄": "pregnant person 妊娠",
	"🤱": "breast-feeding nursing baby 授乳 母乳",
	"👼": "baby angel cherub 天使 エンジェル",
	"🎅": "Santa Claus Christmas サンタクロース クリスマス",
	"🤶": "Mrs. Claus Christmas サンタ夫人 クリスマス",
	"🦸": "superhero power hero ヒーロー スーパーヒーロー",
	"🦹": "supervillain evil villain ヴィラン 悪役",
	"🧙": "mage wizard magic 魔法使い ウィザード",
	"🧚": "fairy magical pixie 妖精 フェアリー",
	"🧛": "vampire dracula blood 吸血鬼 バンパイア",
	"🧜": "merperson mermaid sea 人魚 マーメイド",
	"🧝": "elf fantasy pointy ears エルフ 妖精",
	"🧞": "genie lamp magic ジーニー ランプ",
	"🧟": "zombie undead ゾンビ アンデッド",
	"💆": "person getting massage spa relax マッサージ リラックス",
	"💇": "person getting haircut salon 散髪 美容院",
	"🚶": "person walking pedestrian 歩く 歩行者",
	"🧍": "person standing upright 立つ 起立",
	"🧎": "person kneeling bow ひざまずく 正座",
	"🏃": "person running jog sprint 走る ランニング",
	"💃": "woman dancing salsa dress ダンス 踊り",
	"🕺": "man dancing disco ダンス 踊り",
	"🕴️": "person in suit levitating business 浮遊 スーツ",
	"👯": "people with bunny ears dancing party バニー ダンス",
	"🧖": "person in steamy room sauna spa サウナ",
	"🧗": "person climbing rock wall クライミング 登る",
	"🤸": "person cartwheeling gymnastics 側転 体操",
	"🏌️": "person golfing golf swing ゴルフ",
	"🏇": "horse racing jockey 競馬 ジョッキー",
	"⛷️": "skier snow winter スキー",
	"🏂": "snowboarder snow winter スノーボード",
	"🏋️": "person lifting weights gym strong ウェイトリフティング ジム",
	"🤼": "people wrestling sport レスリング",
	"🤽": "person playing water polo 水球",
	"🤾": "person playing handball ハンドボール",
	"🤺": "person fencing sword フェンシング 剣",
	"⛹️": "person bouncing ball basketball バスケ ドリブル",
	"🏄": "person surfing wave ocean サーフィン 波",
	"🚣": "person rowing boat ボート 漕ぐ",
	"🧘": "person in lotus position yoga meditation ヨガ 瞑想 座禅",
	"🏊": "person swimming pool water 水泳 プール",
	"🚴": "person biking cycling bicycle 自転車",
	"🚵": "person mountain biking MTB マウンテンバイク",
	"🛀": "person taking bath bathtub お風呂 入浴",
	"🛌": "person in bed sleeping 寝る ベッド",
	"👭": "women holding hands friends female 女性同士 手をつなぐ",
	"👫": "woman and man holding hands couple カップル 手をつなぐ",
	"👬": "men holding hands friends male 男性同士 手をつなぐ",
	"💏": "kiss couple love キス カップル",
	"💑": "couple with heart love relationship カップル ハート",
	"👪": "family parents children 家族 ファミリー",
	"🗣️": "speaking head voice talk 話す 声",
	"👤": "bust in silhouette person user 人影 ユーザー",
	"👥": "busts in silhouette people group 人影 グループ",
	"🫂": "people hugging embrace 抱擁 ハグ",
	"👣": "footprints tracks walking 足跡 あしあと",

	// ==================== ANIMALS & NATURE ====================
	"🐶": "dog face puppy pet 犬 いぬ わんわん",
	"🐕": "dog pet canine 犬",
	"🦮": "guide dog service 盲導犬",
	"🐕‍🦺": "service dog assistance 介助犬",
	"🐩": "poodle dog fancy プードル",
	"🐺": "wolf howl wild オオカミ 狼",
	"🦊": "fox face cunning きつね 狐",
	"🦝": "raccoon bandit mask アライグマ ラクーン",
	"🐱": "cat face kitten pet 猫 ねこ にゃー",
	"🐈": "cat pet feline 猫",
	"🐈‍⬛": "black cat superstition 黒猫",
	"🦁": "lion face king jungle ライオン 獅子",
	"🐯": "tiger face stripes 虎 とら",
	"🐅": "tiger big cat 虎 タイガー",
	"🐆": "leopard spots cheetah ヒョウ 豹",
	"🐴": "horse face ride 馬 うま",
	"🫎": "moose elk ヘラジカ ムース",
	"🫏": "donkey burro ロバ",
	"🐎": "horse racing gallop 馬 競馬",
	"🦄": "unicorn magical horn ユニコーン 一角獣",
	"🦓": "zebra stripes シマウマ",
	"🦌": "deer stag 鹿 しか",
	"🦬": "bison buffalo バイソン",
	"🐮": "cow face moo 牛 うし",
	"🐂": "ox strong 雄牛",
	"🐃": "water buffalo 水牛",
	"🐄": "cow dairy milk 乳牛",
	"🐷": "pig face oink 豚 ぶた",
	"🐖": "pig farm pork 豚",
	"🐗": "boar wild pig 猪 いのしし",
	"🐽": "pig nose snout 豚の鼻",
	"🐏": "ram sheep horn 牡羊 ラム",
	"🐑": "ewe sheep lamb 羊 ひつじ",
	"🐐": "goat mountain 山羊 やぎ",
	"🐪": "camel one hump ラクダ 一こぶ",
	"🐫": "two-hump camel bactrian ラクダ 二こぶ",
	"🦙": "llama alpaca リャマ アルパカ",
	"🦒": "giraffe tall spots キリン",
	"🐘": "elephant trunk 象 ぞう",
	"🦣": "mammoth extinct ice age マンモス",
	"🦏": "rhinoceros horn サイ",
	"🦛": "hippopotamus hippo カバ",
	"🐭": "mouse face small ネズミ ねずみ",
	"🐁": "mouse rodent ネズミ",
	"🐀": "rat rodent ネズミ ラット",
	"🐹": "hamster face pet ハムスター",
	"🐰": "rabbit face bunny うさぎ ウサギ",
	"🐇": "rabbit bunny hop うさぎ",
	"🐿️": "chipmunk squirrel リス シマリス",
	"🦫": "beaver dam ビーバー",
	"🦔": "hedgehog spiny ハリネズミ",
	"🦇": "bat nocturnal vampire コウモリ 蝙蝠",
	"🐻": "bear face brown 熊 くま",
	"🐻‍❄️": "polar bear arctic white 白熊 シロクマ",
	"🐨": "koala face bear コアラ",
	"🐼": "panda face bamboo パンダ",
	"🦥": "sloth lazy slow ナマケモノ",
	"🦦": "otter swimming cute カワウソ",
	"🦨": "skunk stink smell スカンク",
	"🦘": "kangaroo joey pouch カンガルー",
	"🦡": "badger animal アナグマ",
	"🐾": "paw prints animal tracks 肉球 足跡",
	"🐔": "chicken hen poultry 鶏 にわとり",
	"🐓": "rooster cock crow 雄鶏 おんどり",
	"🐣": "hatching chick baby ひよこ 孵化",
	"🐤": "baby chick bird ひよこ",
	"🐥": "front-facing baby chick ひよこ",
	"🐦": "bird tweet chirp 鳥 とり",
	"🐧": "penguin cold ice ペンギン",
	"🕊️": "dove peace olive 鳩 平和",
	"🦅": "eagle prey raptor 鷲 わし",
	"🦆": "duck quack アヒル かも 鴨",
	"🦢": "swan graceful white 白鳥 スワン",
	"🦉": "owl night wise フクロウ 梟",
	"🦤": "dodo extinct bird ドードー",
	"🪶": "feather light bird 羽 羽根",
	"🦩": "flamingo pink bird フラミンゴ",
	"🦚": "peacock tail feathers 孔雀 クジャク",
	"🦜": "parrot colorful bird オウム インコ",
	"🐸": "frog face toad カエル 蛙",
	"🐊": "crocodile reptile alligator ワニ 鰐",
	"🐢": "turtle tortoise slow 亀 かめ カメ",
	"🦎": "lizard reptile gecko トカゲ",
	"🐍": "snake serpent slither 蛇 へび ヘビ",
	"🐲": "dragon face Chinese 竜 龍 ドラゴン",
	"🐉": "dragon mythical Chinese 竜 龍",
	"🦕": "sauropod dinosaur long neck 恐竜 首長竜",
	"🦖": "t-rex dinosaur tyrannosaurus 恐竜 ティラノ",
	"🐳": "spouting whale ocean 鯨 クジラ 潮吹き",
	"🐋": "whale humpback ocean クジラ 鯨",
	"🐬": "dolphin ocean smart イルカ",
	"🦭": "seal marine ocean アザラシ",
	"🐟": "fish swim ocean 魚 さかな",
	"🐠": "tropical fish colorful 熱帯魚",
	"🐡": "blowfish puffer フグ 河豚",
	"🦈": "shark predator ocean サメ 鮫",
	"🐙": "octopus tentacles ocean タコ 蛸",
	"🐚": "spiral shell sea 貝殻 巻き貝",
	"🪸": "coral reef ocean サンゴ 珊瑚",
	"🪼": "jellyfish ocean クラゲ 海月",
	"🐌": "snail slow shell カタツムリ 蝸牛",
	"🦋": "butterfly wings beautiful 蝶 ちょうちょ",
	"🐛": "bug caterpillar insect 虫 毛虫 イモムシ",
	"🐜": "ant insect colony 蟻 アリ",
	"🐝": "honeybee wasp buzz 蜂 ミツバチ ハチ",
	"🪲": "beetle bug insect 甲虫 カブトムシ",
	"🐞": "ladybug ladybird beetle てんとう虫",
	"🦗": "cricket chirp insect コオロギ",
	"🪳": "cockroach bug pest ゴキブリ",
	"🕷️": "spider web arachnid クモ 蜘蛛",
	"🕸️": "spider web cobweb クモの巣 蜘蛛の巣",
	"🦂": "scorpion sting サソリ 蠍",
	"🦟": "mosquito bug bite 蚊 カ",
	"🪰": "fly insect bug ハエ 蠅",
	"🪱": "worm earthworm ミミズ 虫",
	"💐": "bouquet flowers gift 花束 ブーケ",
	"🌸": "cherry blossom spring sakura 桜 さくら 花 春",
	"💮": "white flower good mark 花丸 よくできました",
	"🪷": "lotus flower Buddhism 蓮 ハス",
	"🏵️": "rosette award flower ロゼット 花飾り",
	"🌹": "rose flower love red バラ 薔薇",
	"🥀": "wilted flower dead sad 枯れた花 しおれ",
	"🌺": "hibiscus flower tropical ハイビスカス",
	"🌻": "sunflower sun yellow ひまわり 向日葵",
	"🌼": "blossom flower bloom 花 開花",
	"🌷": "tulip flower spring チューリップ",
	"🪻": "hyacinth flower ヒヤシンス",
	"🌱": "seedling sprout growing 芽 新芽 苗",
	"🪴": "potted plant indoor 鉢植え 観葉植物",
	"🌲": "evergreen tree pine conifer 松 針葉樹",
	"🌳": "deciduous tree oak leaf 木 広葉樹",
	"🌴": "palm tree tropical beach ヤシ 南国",
	"🌵": "cactus desert prickly サボテン",
	"🌾": "sheaf of rice grain harvest 稲 稲穂 米",
	"🌿": "herb leaf green ハーブ 葉",
	"☘️": "shamrock Ireland clover シャムロック クローバー",
	"🍀": "four leaf clover luck fortune 四つ葉 クローバー 幸運",
	"🍁": "maple leaf autumn fall Canada 紅葉 もみじ 秋",
	"🍂": "fallen leaf autumn brown 落ち葉 枯れ葉",
	"🍃": "leaf fluttering wind green 葉 風",
	"🪹": "empty nest bird 空の巣",
	"🪺": "nest with eggs bird 巣 卵",
	"🍄": "mushroom fungus toadstool きのこ キノコ",
	"☀️": "sun sunny bright weather 太陽 晴れ 天気",
	"🌤️": "sun behind small cloud partly cloudy 晴れ時々曇り",
	"⛅": "sun behind cloud partly cloudy 曇り時々晴れ",
	"🌥️": "sun behind large cloud mostly cloudy 曇りがち",
	"☁️": "cloud overcast weather 雲 曇り",
	"🌦️": "sun behind rain cloud shower 天気雨",
	"🌧️": "cloud with rain rainy 雨 雨雲",
	"⛈️": "cloud with lightning rain thunderstorm 雷雨 嵐",
	"🌩️": "cloud with lightning thunder 雷 稲妻",
	"🌨️": "cloud with snow snowfall 雪 降雪",
	"❄️": "snowflake cold winter ice 雪 結晶 冬",
	"☃️": "snowman winter cold 雪だるま 冬",
	"⛄": "snowman without snow winter 雪だるま",
	"🌬️": "wind face blowing 風 吹く",
	"🌪️": "tornado twister storm 竜巻 トルネード",
	"🌫️": "fog mist haze 霧 もや",
	"🌈": "rainbow colors weather 虹 にじ",
	"☔": "umbrella rain rainy 傘 雨",
	"💧": "droplet water tear 水滴 雫",
	"🌊": "water wave ocean surf 波 海 サーフ",

	// ==================== FOOD & DRINK ====================
	"🍇": "grapes purple wine ぶどう 葡萄",
	"🍈": "melon cantaloupe fruit メロン",
	"🍉": "watermelon summer fruit スイカ 西瓜",
	"🍊": "tangerine orange mandarin みかん オレンジ",
	"🍋": "lemon citrus sour レモン 檸檬",
	"🍌": "banana yellow fruit バナナ",
	"🍍": "pineapple tropical fruit パイナップル",
	"🥭": "mango tropical fruit マンゴー",
	"🍎": "red apple fruit healthy りんご 林檎 赤",
	"🍏": "green apple fruit healthy 青りんご",
	"🍐": "pear fruit 梨 洋梨",
	"🍑": "peach fruit fuzzy 桃 もも",
	"🍒": "cherries red fruit さくらんぼ チェリー",
	"🍓": "strawberry red berry いちご 苺",
	"🫐": "blueberries berry fruit ブルーベリー",
	"🥝": "kiwi fruit green キウイ",
	"🍅": "tomato vegetable red トマト",
	"🫒": "olive green oil オリーブ",
	"🥥": "coconut palm tropical ココナッツ",
	"🥑": "avocado green healthy アボカド",
	"🍆": "eggplant aubergine purple ナス 茄子",
	"🥔": "potato starch root じゃがいも ポテト",
	"🥕": "carrot orange vegetable にんじん 人参",
	"🌽": "ear of corn maize とうもろこし",
	"🌶️": "hot pepper chili spicy 唐辛子 辛い",
	"🫑": "bell pepper capsicum green ピーマン パプリカ",
	"🥒": "cucumber green fresh きゅうり",
	"🥬": "leafy green vegetable salad 葉野菜 白菜 レタス",
	"🥦": "broccoli vegetable green ブロッコリー",
	"🧄": "garlic clove flavor にんにく ニンニク",
	"🧅": "onion cook cry 玉ねぎ タマネギ",
	"🥜": "peanuts groundnut ピーナッツ 落花生",
	"🫘": "beans legume 豆 ビーンズ",
	"🌰": "chestnut autumn nut 栗 くり",
	"🍞": "bread loaf bakery パン 食パン",
	"🥐": "croissant pastry French クロワッサン",
	"🥖": "baguette bread French フランスパン バゲット",
	"🫓": "flatbread naan pita ナン フラットブレッド",
	"🥨": "pretzel twisted snack プレッツェル",
	"🥯": "bagel bread round ベーグル",
	"🥞": "pancakes breakfast syrup パンケーキ ホットケーキ",
	"🧇": "waffle breakfast ワッフル",
	"🧀": "cheese wedge dairy チーズ",
	"🍖": "meat on bone rib 肉 骨付き",
	"🍗": "poultry leg chicken 鶏肉 チキン",
	"🥩": "cut of meat steak beef ステーキ 肉",
	"🥓": "bacon meat breakfast ベーコン",
	"🍔": "hamburger burger fast food ハンバーガー",
	"🍟": "french fries potato chips ポテト フライドポテト",
	"🍕": "pizza slice cheese ピザ",
	"🌭": "hot dog sausage bun ホットドッグ ソーセージ",
	"🥪": "sandwich bread lunch サンドイッチ",
	"🌮": "taco Mexican food タコス メキシカン",
	"🌯": "burrito wrap Mexican ブリトー",
	"🫔": "tamale Mexican タマル",
	"🥙": "stuffed flatbread pita falafel ピタパン ファラフェル",
	"🧆": "falafel chickpea ファラフェル",
	"🥚": "egg breakfast 卵 たまご",
	"🍳": "cooking egg fried sunny side 目玉焼き 料理",
	"🥘": "shallow pan of food paella stew パエリア 鍋",
	"🍲": "pot of food stew soup 鍋 シチュー",
	"🫕": "fondue cheese chocolate フォンデュ",
	"🥣": "bowl with spoon cereal soup シリアル スープ",
	"🥗": "green salad healthy サラダ",
	"🍿": "popcorn movie snack ポップコーン 映画",
	"🧈": "butter dairy spread バター",
	"🧂": "salt seasoning 塩 しお",
	"🥫": "canned food tin 缶詰 缶",
	"🍱": "bento box Japanese lunch 弁当 べんとう",
	"🍘": "rice cracker senbei おせんべい 煎餅",
	"🍙": "rice ball onigiri おにぎり 🍙",
	"🍚": "cooked rice bowl ご飯 白米",
	"🍛": "curry rice Japanese カレー カレーライス",
	"🍜": "steaming bowl ramen noodle ラーメン 麺",
	"🍝": "spaghetti pasta Italian スパゲッティ パスタ",
	"🍠": "roasted sweet potato yam 焼き芋 さつまいも",
	"🍢": "oden skewer Japanese おでん 串",
	"🍣": "sushi Japanese fish 寿司 すし",
	"🍤": "fried shrimp tempura エビフライ 天ぷら",
	"🍥": "fish cake naruto narutomaki なると 蒲鉾",
	"🥮": "moon cake Chinese festival 月餅 げっぺい",
	"🍡": "dango dumpling Japanese 団子 だんご",
	"🥟": "dumpling gyoza potsticker 餃子 ぎょうざ",
	"🥠": "fortune cookie Chinese フォーチュンクッキー",
	"🥡": "takeout box Chinese 中華テイクアウト",
	"🦀": "crab shellfish カニ 蟹",
	"🦞": "lobster shellfish ロブスター",
	"🦐": "shrimp prawn seafood エビ 海老",
	"🦑": "squid tentacle seafood イカ 烏賊",
	"🦪": "oyster pearl shellfish 牡蠣 カキ",
	"🍦": "soft ice cream cone ソフトクリーム",
	"🍧": "shaved ice syrup かき氷",
	"🍨": "ice cream sundae アイスクリーム",
	"🍩": "doughnut donut sweet ドーナツ",
	"🍪": "cookie biscuit sweet クッキー ビスケット",
	"🎂": "birthday cake candles celebration 誕生日ケーキ お祝い",
	"🍰": "shortcake strawberry dessert ショートケーキ",
	"🧁": "cupcake muffin sweet カップケーキ マフィン",
	"🥧": "pie dessert baked パイ",
	"🍫": "chocolate bar sweet チョコレート",
	"🍬": "candy sweet wrapper 飴 キャンディ お菓子",
	"🍭": "lollipop candy stick 棒つきキャンディ ペロペロキャンディ",
	"🍮": "custard pudding flan プリン カスタード",
	"🍯": "honey pot sweet はちみつ ハニー",
	"🍼": "baby bottle milk formula 哺乳瓶 ミルク",
	"🥛": "glass of milk dairy 牛乳 ミルク",
	"☕": "hot beverage coffee tea コーヒー 珈琲 お茶",
	"🫖": "teapot brew steep ティーポット 急須",
	"🍵": "teacup without handle matcha green tea お茶 抹茶 緑茶",
	"🍶": "sake bottle cup 日本酒 酒 徳利",
	"🍾": "bottle with popping cork champagne celebrate シャンパン 祝い",
	"🍷": "wine glass red white ワイン グラス",
	"🍸": "cocktail glass martini カクテル マティーニ",
	"🍹": "tropical drink cocktail umbrella トロピカルドリンク",
	"🍺": "beer mug draft ビール 生ビール",
	"🍻": "clinking beer mugs cheers toast 乾杯 ビール",
	"🥂": "clinking glasses champagne toast 乾杯 グラス",
	"🥃": "tumbler glass whiskey bourbon ウイスキー タンブラー",
	"🫗": "pouring liquid pour 注ぐ",
	"🥤": "cup with straw soda drink ストロー ジュース",
	"🧋": "bubble tea boba tapioca タピオカ ボバ",
	"🧃": "beverage box juice pack ジュース パック",
	"🧉": "mate herb tea マテ茶",
	"🧊": "ice cube cold frozen 氷 アイス",
	"🥢": "chopsticks Asian eating 箸 はし",
	"🍽️": "fork and knife plate dinner ディナー 皿",
	"🍴": "fork and knife eating 食事 フォーク ナイフ",
	"🥄": "spoon utensil eat スプーン",
	"🔪": "kitchen knife cooking chef 包丁 ナイフ 料理",
	"🫙": "jar container 瓶 ジャー",
	"🏺": "amphora vase pottery 壺 アンフォラ",

	// ==================== ACTIVITIES ====================
	"🎃": "jack-o-lantern Halloween pumpkin ハロウィン かぼちゃ",
	"🎄": "Christmas tree holiday 🎄 クリスマスツリー",
	"🎆": "fireworks celebration 花火 お祝い",
	"🎇": "sparkler fireworks 線香花火",
	"🧨": "firecracker dynamite boom 爆竹",
	"✨": "sparkles shine glitter magic キラキラ 輝き",
	"🎈": "balloon party celebration 風船 パーティ",
	"🎉": "party popper tada congratulations おめでとう パーティ",
	"🎊": "confetti ball celebration お祝い 紙吹雪",
	"🎋": "tanabata tree wish 七夕 短冊",
	"🎍": "pine decoration kadomatsu new year 門松 正月",
	"🎎": "Japanese dolls hinamatsuri ひな祭り お雛様",
	"🎏": "carp streamer koinobori children 鯉のぼり こどもの日",
	"🎐": "wind chime summer sound 風鈴 夏",
	"🎑": "moon viewing ceremony tsukimi お月見 月見",
	"🧧": "red envelope lucky money お年玉 紅包",
	"🎀": "ribbon bow gift リボン 飾り プレゼント",
	"🎁": "wrapped gift present birthday プレゼント 贈り物",
	"🎗️": "reminder ribbon awareness リボン 啓発",
	"🎟️": "admission tickets entry 入場券 チケット",
	"🎫": "ticket admission pass チケット 切符",
	"🎖️": "military medal honor 勲章 メダル",
	"🏆": "trophy winner champion トロフィー 優勝 チャンピオン",
	"🏅": "sports medal award 賞 メダル",
	"🥇": "1st place gold medal first 金メダル 一位",
	"🥈": "2nd place silver medal second 銀メダル 二位",
	"🥉": "3rd place bronze medal third 銅メダル 三位",
	"⚽": "soccer ball football サッカー",
	"⚾": "baseball ball sport 野球 ベースボール",
	"🥎": "softball ball sport ソフトボール",
	"🏀": "basketball ball hoop バスケ バスケットボール",
	"🏐": "volleyball ball sport バレーボール",
	"🏈": "american football gridiron アメフト アメリカンフットボール",
	"🏉": "rugby football ball ラグビー",
	"🎾": "tennis ball racket テニス",
	"🥏": "flying disc frisbee ultimate フリスビー",
	"🎳": "bowling ball pins ボウリング",
	"🏏": "cricket bat ball クリケット",
	"🏑": "field hockey stick ホッケー",
	"🏒": "ice hockey stick puck アイスホッケー",
	"🥍": "lacrosse stick ball ラクロス",
	"🏓": "ping pong table tennis 卓球 ピンポン",
	"🏸": "badminton racquet shuttlecock バドミントン",
	"🥊": "boxing glove punch fight ボクシング グローブ",
	"🥋": "martial arts uniform karate judo 空手 柔道 道着",
	"🥅": "goal net ゴール ネット",
	"⛳": "flag in hole golf ゴルフ",
	"⛸️": "ice skate skating figure スケート アイススケート",
	"🎣": "fishing pole rod 釣り フィッシング",
	"🤿": "diving mask snorkel ダイビング シュノーケル",
	"🎽": "running shirt jersey ゼッケン ランニング",
	"🎿": "skis skiing snow winter スキー 雪",
	"🛷": "sled sledge toboggan ソリ",
	"🥌": "curling stone ice カーリング",
	"🎯": "bullseye target dart direct hit 的 ダーツ 命中",
	"🪀": "yo-yo toy play ヨーヨー",
	"🪁": "kite flying wind 凧 たこ",
	"🔫": "water pistol gun squirt 水鉄砲",
	"🎱": "pool 8 ball billiards ビリヤード",
	"🔮": "crystal ball fortune psychic 水晶玉 占い",
	"🪄": "magic wand spell wizard 魔法の杖",
	"🧿": "nazar amulet evil eye ナザール お守り",
	"🪬": "hamsa amulet protection ハムサ 魔除け",
	"🎮": "video game controller gamepad ゲーム コントローラー",
	"🕹️": "joystick arcade game ジョイスティック ゲーム",
	"🎰": "slot machine casino gamble スロット カジノ",
	"🎲": "game die dice chance サイコロ ダイス",
	"🧩": "puzzle piece jigsaw パズル ピース",
	"🧸": "teddy bear toy stuffed ぬいぐるみ テディベア",
	"🪅": "pinata party candy ピニャータ",
	"🪩": "mirror ball disco dance ミラーボール ディスコ",
	"🪆": "nesting dolls matryoshka マトリョーシカ",
	"♠️": "spade suit cards poker スペード トランプ",
	"♥️": "heart suit cards poker ハート トランプ",
	"♦️": "diamond suit cards poker ダイヤ トランプ",
	"♣️": "club suit cards poker クラブ トランプ",
	"♟️": "chess pawn piece チェス ポーン",
	"🃏": "joker card wild ジョーカー トランプ",
	"🀄": "mahjong red dragon tile 麻雀 マージャン 中",
	"🎭": "performing arts theater drama mask 演劇 仮面 劇場",
	"🖼️": "framed picture painting art 額縁 絵画",
	"🎨": "artist palette paint color art 絵 アート パレット",
	"🧵": "thread sewing needle 糸 縫い物",
	"🪡": "sewing needle stitch 縫い針",
	"🧶": "yarn knitting crochet 毛糸 編み物",
	"🪢": "knot rope 結び目 ロープ",

	// ==================== TRAVEL & PLACES ====================
	"🌍": "globe Europe Africa earth world 地球 世界 ヨーロッパ アフリカ",
	"🌎": "globe Americas earth world 地球 アメリカ",
	"🌏": "globe Asia Australia earth world 地球 アジア オーストラリア",
	"🌐": "globe with meridians internet web グローブ インターネット",
	"🗺️": "world map geography 世界地図",
	"🧭": "compass navigation direction コンパス 方角",
	"🏔️": "snow-capped mountain peak 雪山 山頂",
	"⛰️": "mountain hill peak 山",
	"🌋": "volcano eruption lava 火山 噴火",
	"🗻": "mount fuji Japan 富士山",
	"🏕️": "camping tent outdoor キャンプ テント",
	"🏖️": "beach umbrella sand sun ビーチ 砂浜 海岸",
	"🏜️": "desert sand dry 砂漠",
	"🏝️": "desert island tropical 無人島 島",
	"🏞️": "national park nature scenery 国立公園 自然",
	"🏟️": "stadium arena sport スタジアム 競技場",
	"🏛️": "classical building columns 古代建築 神殿",
	"🏗️": "building construction crane 建設中 クレーン",
	"🧱": "brick wall building レンガ 煉瓦",
	"🪨": "rock stone boulder 岩 石",
	"🪵": "wood log timber 木材 丸太",
	"🛖": "hut shelter cabin 小屋",
	"🏘️": "houses neighborhood 住宅街 近所",
	"🏚️": "derelict house abandoned 廃墟 空き家",
	"🏠": "house home residence 家 自宅 ホーム",
	"🏡": "house with garden yard 家 庭付き",
	"🏢": "office building work ビル オフィス 会社",
	"🏣": "Japanese post office 郵便局",
	"🏤": "post office mail 郵便局",
	"🏥": "hospital medical health 病院 医療",
	"🏦": "bank money finance 銀行 お金",
	"🏨": "hotel lodging stay ホテル 宿泊",
	"🏩": "love hotel couples ラブホテル",
	"🏪": "convenience store shop コンビニ 店",
	"🏫": "school education learn 学校 教育",
	"🏬": "department store shopping デパート 百貨店",
	"🏭": "factory industrial manufacturing 工場 製造",
	"🏯": "Japanese castle historic 城 お城 日本",
	"🏰": "castle European medieval 城 西洋 中世",
	"💒": "wedding chapel marriage 結婚式場 チャペル",
	"🗼": "Tokyo tower landmark 東京タワー",
	"🗽": "Statue of Liberty New York 自由の女神 ニューヨーク",
	"⛪": "church cathedral Christian 教会 聖堂",
	"🕌": "mosque Islamic Muslim モスク イスラム",
	"🛕": "hindu temple worship ヒンドゥー寺院",
	"🕍": "synagogue Jewish シナゴーグ ユダヤ",
	"⛩️": "shinto shrine torii gate 神社 鳥居",
	"🕋": "kaaba Mecca Islam カーバ メッカ",
	"⛲": "fountain water park 噴水 公園",
	"⛺": "tent camping outdoor テント キャンプ",
	"🌁": "foggy bridge San Francisco 霧 橋",
	"🌃": "night with stars city skyline 夜景 星空",
	"🏙️": "cityscape buildings skyline 都市 ビル群",
	"🌄": "sunrise over mountains morning 日の出 山",
	"🌅": "sunrise ocean morning 日の出 海",
	"🌆": "cityscape at dusk evening 夕暮れ 都市",
	"🌇": "sunset city evening 夕日 日没",
	"🌉": "bridge at night city 橋 夜景",
	"🌌": "milky way galaxy stars 天の川 銀河 宇宙",
	"♨️": "hot springs onsen spa 温泉 ♨",
	"🎠": "carousel horse merry-go-round 回転木馬 メリーゴーランド",
	"🛝": "playground slide park 滑り台 遊具",
	"🎡": "ferris wheel amusement park 観覧車 遊園地",
	"🎢": "roller coaster amusement park ジェットコースター 遊園地",
	"💈": "barber pole haircut 床屋 理髪店",
	"🎪": "circus tent show サーカス テント",
	"🚂": "locomotive steam train 機関車 蒸気",
	"🚃": "railway car train 客車",
	"🚄": "high-speed train bullet 新幹線 高速",
	"🚅": "bullet train shinkansen 新幹線",
	"🚆": "train rail transit 電車 列車",
	"🚇": "metro subway underground 地下鉄 メトロ",
	"🚈": "light rail transit ライトレール",
	"🚉": "station platform 駅 ステーション",
	"🚊": "tram streetcar trolley 路面電車",
	"🚝": "monorail transit モノレール",
	"🚞": "mountain railway train 登山鉄道",
	"🚋": "tram car streetcar 路面電車",
	"🚌": "bus transit public バス 公共交通",
	"🚍": "oncoming bus front バス 正面",
	"🚎": "trolleybus electric トロリーバス",
	"🚐": "minibus van shuttle マイクロバス",
	"🚑": "ambulance emergency medical 救急車 緊急",
	"🚒": "fire engine truck 消防車",
	"🚓": "police car patrol パトカー 警察",
	"🚔": "oncoming police car パトカー 正面",
	"🚕": "taxi cab ride タクシー",
	"🚖": "oncoming taxi front タクシー 正面",
	"🚗": "automobile car vehicle 車 自動車",
	"🚘": "oncoming automobile car 車 正面",
	"🚙": "sport utility vehicle SUV RV SUV 車",
	"🛻": "pickup truck vehicle ピックアップトラック",
	"🚚": "delivery truck shipping 配送 トラック 配達",
	"🚛": "articulated lorry semi truck 大型トラック",
	"🚜": "tractor farm agriculture トラクター 農業",
	"🏎️": "racing car formula speed レーシングカー F1",
	"🏍️": "motorcycle bike racing オートバイ バイク",
	"🛵": "motor scooter vespa スクーター 原付",
	"🦽": "manual wheelchair 車椅子 手動",
	"🦼": "motorized wheelchair electric 電動車椅子",
	"🛺": "auto rickshaw tuk-tuk オートリキシャ",
	"🚲": "bicycle bike cycling 自転車 チャリ",
	"🛴": "kick scooter キックボード",
	"🛹": "skateboard ride スケートボード",
	"🛼": "roller skate skating ローラースケート",
	"🚏": "bus stop sign バス停",
	"🛣️": "motorway highway road 高速道路",
	"🛤️": "railway track train 線路 レール",
	"🛞": "wheel tire car タイヤ 車輪",
	"⛽": "fuel pump gas station ガソリン 給油",
	"🚨": "police car light emergency 赤色灯 パトライト 緊急",
	"🚥": "horizontal traffic light signal 信号機 横",
	"🚦": "vertical traffic light signal 信号機 縦",
	"🛑": "stop sign octagon 停止 ストップ",
	"🚧": "construction sign barrier 工事中 バリケード",
	"⚓": "anchor ship port 錨 いかり",
	"🛟": "ring buoy life saver 浮き輪 救命",
	"⛵": "sailboat yacht wind ヨット 帆船",
	"🛶": "canoe kayak paddle カヌー カヤック",
	"🚤": "speedboat motorboat fast スピードボート",
	"🛳️": "passenger ship cruise クルーズ船 旅客船",
	"⛴️": "ferry boat ship フェリー",
	"🛥️": "motor boat yacht モーターボート",
	"🚢": "ship ocean vessel 船 大型船",
	"✈️": "airplane flight travel 飛行機 空の旅",
	"🛩️": "small airplane private jet 小型飛行機",
	"🛫": "airplane departure takeoff 飛行機 離陸 出発",
	"🛬": "airplane arrival landing 飛行機 着陸 到着",
	"🪂": "parachute skydive パラシュート スカイダイビング",
	"💺": "seat chair airplane 座席 飛行機の座席",
	"🚁": "helicopter chopper ヘリコプター",
	"🚟": "suspension railway monorail 懸垂式モノレール",
	"🚠": "mountain cableway gondola ゴンドラ ロープウェイ",
	"🚡": "aerial tramway cable car ロープウェイ",
	"🛸": "flying saucer UFO spaceship UFO 円盤 宇宙船",
	"🚀": "rocket launch space ロケット 宇宙 打ち上げ",
	"🛰️": "satellite orbit space 人工衛星",
	"🕐": "one o'clock 1:00 1時",
	"🕑": "two o'clock 2:00 2時",
	"🕒": "three o'clock 3:00 3時",
	"🕓": "four o'clock 4:00 4時",
	"🕔": "five o'clock 5:00 5時",
	"🕕": "six o'clock 6:00 6時",
	"🕖": "seven o'clock 7:00 7時",
	"🕗": "eight o'clock 8:00 8時",
	"🕘": "nine o'clock 9:00 9時",
	"🕙": "ten o'clock 10:00 10時",
	"🕚": "eleven o'clock 11:00 11時",
	"🕛": "twelve o'clock 12:00 12時",
	"🕜": "one-thirty 1:30",
	"🕝": "two-thirty 2:30",
	"🕞": "three-thirty 3:30",
	"🕟": "four-thirty 4:30",
	"🕠": "five-thirty 5:30",
	"🕡": "six-thirty 6:30",
	"🕢": "seven-thirty 7:30",
	"🕣": "eight-thirty 8:30",
	"🕤": "nine-thirty 9:30",
	"🕥": "ten-thirty 10:30",
	"🕦": "eleven-thirty 11:30",
	"🕧": "twelve-thirty 12:30",
	"🌑": "new moon dark night 新月 朔",
	"🌒": "waxing crescent moon 三日月",
	"🌓": "first quarter moon half 上弦の月",
	"🌔": "waxing gibbous moon 十三夜月",
	"🌕": "full moon bright night 満月 望月",
	"🌖": "waning gibbous moon 十六夜",
	"🌗": "last quarter moon half 下弦の月",
	"🌘": "waning crescent moon 二十六夜",
	"🌙": "crescent moon night sleep 三日月 月",
	"🌚": "new moon face dark 新月 顔",
	"🌛": "first quarter moon face 上弦の月 顔",
	"🌜": "last quarter moon face 下弦の月 顔",
	"🌡️": "thermometer temperature 温度計 体温計",
	"🌝": "full moon face bright 満月 顔",
	"🌞": "sun with face bright warm 太陽 顔",
	"🪐": "ringed planet Saturn 土星 惑星",
	"⭐": "star yellow favorite 星 お気に入り",
	"🌟": "glowing star shine sparkle 輝く星 キラキラ",

	// ==================== OBJECTS ====================
	"👓": "glasses eyeglasses spectacles メガネ 眼鏡",
	"🕶️": "sunglasses cool dark サングラス",
	"🥽": "goggles safety lab ゴーグル 安全",
	"🥼": "lab coat science doctor 白衣 研究",
	"🦺": "safety vest high visibility 安全ベスト 反射",
	"👔": "necktie business formal ネクタイ ビジネス",
	"👕": "t-shirt casual top Tシャツ",
	"👖": "jeans pants denim ジーンズ ズボン",
	"🧣": "scarf winter warm マフラー スカーフ",
	"🧤": "gloves winter warm 手袋",
	"🧥": "coat jacket winter コート ジャケット",
	"🧦": "socks feet warm 靴下 ソックス",
	"👗": "dress woman fashion ドレス ワンピース",
	"👘": "kimono Japanese traditional 着物 和服",
	"🥻": "sari Indian traditional サリー インド",
	"🩱": "one-piece swimsuit bathing ワンピース水着",
	"🩲": "briefs underwear shorts ブリーフ パンツ",
	"🩳": "shorts swim trunks ショートパンツ 短パン",
	"👙": "bikini swimsuit beach ビキニ 水着",
	"👚": "woman's clothes blouse ブラウス 服",
	"🪭": "folding hand fan breeze 扇子",
	"👛": "purse wallet coins 財布 小銭入れ",
	"👜": "handbag purse fashion ハンドバッグ",
	"👝": "clutch bag pouch ポーチ クラッチ",
	"🛍️": "shopping bags mall 買い物袋 ショッピング",
	"🎒": "backpack school bag リュック ランドセル",
	"🩴": "thong sandal flip-flop ビーチサンダル",
	"👞": "man's shoe leather dress 革靴 ビジネスシューズ",
	"👟": "running shoe sneaker athletic スニーカー 運動靴",
	"🥾": "hiking boot outdoor 登山靴 ブーツ",
	"🥿": "flat shoe ballet フラットシューズ",
	"👠": "high-heeled shoe stiletto ハイヒール",
	"👡": "woman's sandal heel サンダル",
	"🩰": "ballet shoes dance ballerina バレエシューズ",
	"👢": "woman's boot fashion ブーツ 長靴",
	"🪮": "hair pick comb afro ヘアピック",
	"👑": "crown king queen royal 王冠 クラウン",
	"👒": "woman's hat sun summer 帽子 つば付き",
	"🎩": "top hat formal gentleman シルクハット 紳士",
	"🎓": "graduation cap degree 卒業帽 学位",
	"🧢": "billed cap baseball キャップ 帽子",
	"🪖": "military helmet army ヘルメット 軍用",
	"⛑️": "rescue worker's helmet safety ヘルメット 救助",
	"📿": "prayer beads rosary 数珠 ロザリオ",
	"💄": "lipstick makeup cosmetic 口紅 リップ",
	"💍": "ring diamond engagement 指輪 リング 婚約",
	"💎": "gem stone diamond jewel precious 宝石 ダイヤモンド",
	"🔇": "muted speaker volume off ミュート 消音",
	"🔈": "speaker low volume スピーカー 音量小",
	"🔉": "speaker medium volume スピーカー 音量中",
	"🔊": "speaker high volume loud スピーカー 大音量",
	"📢": "loudspeaker announce public address 拡声器 スピーカー",
	"📣": "megaphone cheer announce メガホン 拡声器",
	"📯": "postal horn bugle ポストホルン",
	"🔔": "bell notification alert ring ベル 通知 鈴",
	"🔕": "bell with slash mute silent ベル 消音",
	"🎼": "musical score sheet music 楽譜 音楽",
	"🎵": "musical note melody song 音符 音楽",
	"🎶": "musical notes melody song 音符 音楽 メロディ",
	"🎙️": "studio microphone podcast recording マイク 録音",
	"🎚️": "level slider mixing audio フェーダー スライダー",
	"🎛️": "control knobs dials audio ツマミ ダイヤル",
	"🎤": "microphone karaoke singing マイク カラオケ",
	"🎧": "headphone headset music audio ヘッドホン 音楽",
	"📻": "radio broadcast FM AM ラジオ",
	"🎷": "saxophone jazz music サックス サクソフォン ジャズ",
	"🪗": "accordion squeeze music アコーディオン",
	"🎸": "guitar rock music acoustic ギター ロック",
	"🎹": "musical keyboard piano keys ピアノ 鍵盤",
	"🎺": "trumpet brass music horn トランペット",
	"🎻": "violin fiddle string music バイオリン",
	"🪕": "banjo string country バンジョー",
	"🥁": "drum beat percussion ドラム 太鼓",
	"🪘": "long drum djembe ジャンベ 太鼓",
	"📱": "mobile phone smartphone cell スマホ 携帯 スマートフォン",
	"📲": "mobile phone with arrow incoming 着信 スマホ",
	"☎️": "telephone phone call 電話 固定電話",
	"📞": "telephone receiver phone call 電話 受話器",
	"📟": "pager beeper ポケベル",
	"📠": "fax machine office ファックス FAX",
	"🔋": "battery power charge バッテリー 電池 充電",
	"🪫": "low battery empty バッテリー低下",
	"🔌": "electric plug power outlet コンセント プラグ",
	"💻": "laptop computer work PC パソコン ラップトップ",
	"🖥️": "desktop computer monitor screen デスクトップ PC モニター",
	"🖨️": "printer paper output プリンター 印刷",
	"⌨️": "keyboard type input キーボード 入力",
	"🖱️": "computer mouse click pointer マウス",
	"🖲️": "trackball input device トラックボール",
	"💽": "computer disk minidisc ディスク",
	"💾": "floppy disk save storage フロッピー 保存",
	"💿": "optical disc CD DVD ディスク",
	"📀": "DVD disc video DVD ディスク",
	"🧮": "abacus calculate math そろばん 算盤",
	"🎥": "movie camera film cinema 映画カメラ シネマ",
	"🎞️": "film frames strip フィルム 映画",
	"📽️": "film projector movie プロジェクター 映写機",
	"🎬": "clapper board film movie action カチンコ 映画",
	"📺": "television TV screen テレビ 📺",
	"📷": "camera photo picture カメラ 写真",
	"📸": "camera with flash photo フラッシュ カメラ",
	"📹": "video camera camcorder ビデオカメラ 録画",
	"📼": "videocassette VHS tape ビデオテープ VHS",
	"🔍": "magnifying glass tilted left search 虫眼鏡 検索 左",
	"🔎": "magnifying glass tilted right search 虫眼鏡 検索 右",
	"🕯️": "candle flame light wax ろうそく キャンドル",
	"💡": "light bulb idea bright electric 電球 アイデア 💡",
	"🔦": "flashlight torch beam 懐中電灯 ライト",
	"🏮": "red paper lantern izakaya Japanese 提灯 赤提灯 居酒屋",
	"🪔": "diya lamp oil ディヤ ランプ",
	"📔": "notebook with decorative cover ノート 手帳",
	"📕": "closed book red 本 赤",
	"📖": "open book reading 本 読書 📖",
	"📗": "green book 本 緑",
	"📘": "blue book 本 青",
	"📙": "orange book 本 オレンジ",
	"📚": "books stack library 本 図書 📚",
	"📓": "notebook journal diary ノート 日記",
	"📒": "ledger notebook record ノート 帳簿",
	"📃": "page with curl document ページ 書類",
	"📜": "scroll parchment ancient 巻物 羊皮紙",
	"📄": "page facing up document file ページ 書類",
	"📰": "newspaper press news 新聞 ニュース",
	"🗞️": "rolled-up newspaper press 新聞 巻き",
	"📑": "bookmark tabs page しおり タブ",
	"🔖": "bookmark save mark しおり ブックマーク",
	"🏷️": "label tag price タグ ラベル 値札",
	"💰": "money bag cash rich お金 金袋",
	"🪙": "coin money metal コイン 硬貨",
	"💴": "yen banknote Japanese money 円 お札 日本円",
	"💵": "dollar banknote US money ドル お札",
	"💶": "euro banknote EU money ユーロ お札",
	"💷": "pound banknote British money ポンド お札",
	"💸": "money with wings flying spending お金 飛ぶ 散財",
	"💳": "credit card payment debit クレジットカード 支払い",
	"🧾": "receipt bill purchase レシート 領収書",
	"💹": "chart increasing with yen stock 株価 上昇 円",
	"✉️": "envelope letter mail 封筒 手紙",
	"📧": "e-mail email メール Eメール",
	"📨": "incoming envelope mail 受信メール",
	"📩": "envelope with arrow sending 送信メール",
	"📤": "outbox tray sent 送信トレイ",
	"📥": "inbox tray received 受信トレイ",
	"📦": "package box delivery parcel 箱 荷物 段ボール 配達",
	"📫": "closed mailbox with raised flag post ポスト 郵便",
	"📪": "closed mailbox with lowered flag empty ポスト 空",
	"📬": "open mailbox with raised flag mail ポスト 郵便あり",
	"📭": "open mailbox with lowered flag empty ポスト 空",
	"📮": "postbox mail letter ポスト 郵便",
	"🗳️": "ballot box vote election 投票箱 選挙",
	"✏️": "pencil write draw 鉛筆 書く",
	"✒️": "black nib pen write 万年筆 ペン先",
	"🖋️": "fountain pen write 万年筆",
	"🖊️": "pen ballpoint write ボールペン",
	"🖌️": "paintbrush art draw 絵筆 ブラシ",
	"🖍️": "crayon draw color クレヨン",
	"📝": "memo note write pencil メモ 書く ノート 📝",
	"💼": "briefcase work business ブリーフケース ビジネス 仕事",
	"📁": "file folder directory フォルダ ファイル",
	"📂": "open file folder directory フォルダ 開く",
	"🗂️": "card index dividers tabs インデックス 仕切り",
	"📅": "calendar date schedule カレンダー 日付 予定",
	"📆": "tear-off calendar page カレンダー 日めくり",
	"🗒️": "spiral notepad memo スパイラルノート メモ帳",
	"🗓️": "spiral calendar date スパイラルカレンダー",
	"📇": "card index rolodex 名刺 索引",
	"📈": "chart increasing up trend グラフ 上昇 📈",
	"📉": "chart decreasing down trend グラフ 下降 📉",
	"📊": "bar chart statistics data グラフ 統計 データ",
	"📋": "clipboard checklist list クリップボード 一覧",
	"📌": "pushpin pin location ピン 画鋲 場所",
	"📍": "round pushpin map location ピン 地図",
	"📎": "paperclip attach clip クリップ 添付",
	"🖇️": "linked paperclips attached クリップ 連結",
	"📏": "straight ruler measure cm 定規 物差し",
	"📐": "triangular ruler angle 三角定規 角度",
	"✂️": "scissors cut trim ハサミ 切る ✂",
	"🗃️": "card file box storage ファイルボックス",
	"🗄️": "file cabinet office キャビネット 棚",
	"🗑️": "wastebasket trash delete remove ゴミ箱 削除",
	"🔒": "locked padlock secure 鍵 ロック 施錠 セキュリティ",
	"🔓": "unlocked padlock open 鍵 解錠 開く",
	"🔏": "locked with pen privacy 鍵 ペン プライバシー",
	"🔐": "locked with key secure 鍵 セキュリティ",
	"🔑": "key lock access 鍵 キー アクセス",
	"🗝️": "old key vintage antique 鍵 古い アンティーク",
	"🔨": "hammer tool build ハンマー 金槌 工具",
	"🪓": "axe chop wood 斧 おの",
	"⛏️": "pick mining dig ピッケル つるはし",
	"⚒️": "hammer and pick mining tools 工具 鉱山",
	"🛠️": "hammer and wrench tools fix 工具 道具 修理",
	"🗡️": "dagger knife blade 短剣 ダガー",
	"⚔️": "crossed swords battle fight 交差した剣 戦い",
	"💣": "bomb explosion danger 爆弾 ボム",
	"🪃": "boomerang return throw ブーメラン",
	"🏹": "bow and arrow archery 弓矢 アーチェリー",
	"🛡️": "shield defense protect 盾 防御",
	"🪚": "carpentry saw wood のこぎり 鋸",
	"🔧": "wrench spanner tool fix レンチ スパナ 修理",
	"🪛": "screwdriver tool fix ドライバー ねじ回し",
	"🔩": "nut and bolt hardware ネジ ボルト ナット",
	"⚙️": "gear cog settings mechanism 歯車 設定 機械",
	"🗜️": "clamp compression vice 万力 クランプ",
	"⚖️": "balance scale justice law 天秤 正義 法律",
	"🦯": "white cane blind 白杖",
	"🔗": "link chain connection リンク チェーン 接続",
	"⛓️": "chains linked bound 鎖 チェーン",
	"🪝": "hook fishing catch フック 鉤",
	"🧰": "toolbox repair fix 工具箱 修理",
	"🧲": "magnet attract pull 磁石 マグネット",
	"🪜": "ladder climb step はしご 梯子",
	"⚗️": "alembic chemistry distill 蒸留器 錬金術",
	"🧪": "test tube science experiment 試験管 実験",
	"🧫": "petri dish biology culture シャーレ 培養",
	"🧬": "DNA double helix genetics 遺伝子 DNA 二重螺旋",
	"🔬": "microscope science research 顕微鏡 科学 研究",
	"🔭": "telescope astronomy stars 望遠鏡 天体観測",
	"📡": "satellite antenna signal アンテナ 衛星 パラボラ",
	"💉": "syringe needle injection vaccine 注射 注射器 ワクチン",
	"🩸": "drop of blood donate red 血 献血",
	"💊": "pill medicine capsule drug 薬 錠剤 カプセル",
	"🩹": "adhesive bandage plaster wound 絆創膏 ばんそうこう",
	"🩼": "crutch injury support 松葉杖",
	"🩺": "stethoscope doctor medical 聴診器 医者",
	"🩻": "x-ray skeleton bone レントゲン 骨",
	"🚪": "door entrance exit open ドア 扉 出入口",
	"🛗": "elevator lift up down エレベーター",
	"🪞": "mirror reflection 鏡 ミラー",
	"🪟": "window glass view 窓",
	"🛏️": "bed sleep bedroom ベッド 寝室 睡眠",
	"🛋️": "couch sofa living room ソファ カウチ",
	"🪑": "chair seat sit 椅子 イス 座る",
	"🚽": "toilet bathroom restroom トイレ 便器 お手洗い",
	"🪠": "plunger toilet unclog プランジャー ラバーカップ",
	"🚿": "shower bath water シャワー",
	"🛁": "bathtub bath soak 浴槽 バスタブ",
	"🪤": "mouse trap catch ネズミ捕り 罠",
	"🪒": "razor shave blade カミソリ 剃刀",
	"🧴": "lotion bottle cream ローション クリーム",
	"🧷": "safety pin fasten 安全ピン",
	"🧹": "broom sweep clean ほうき 掃除",
	"🧺": "basket laundry picnic カゴ 洗濯 ピクニック",
	"🧻": "roll of paper toilet tissue トイレットペーパー ティッシュ",
	"🪣": "bucket pail water バケツ",
	"🧼": "soap clean wash 石鹸 せっけん",
	"🫧": "bubbles soap clean 泡 シャボン",
	"🪥": "toothbrush dental hygiene 歯ブラシ",
	"🧽": "sponge clean absorb スポンジ",
	"🧯": "fire extinguisher safety 消火器",
	"🛒": "shopping cart grocery store ショッピングカート 買い物",
	"⏰": "alarm clock time wake up 目覚まし 時計 アラーム",
	"⏱️": "stopwatch timer ストップウォッチ",
	"⏲️": "timer clock kitchen タイマー キッチン",
	"🕰️": "mantelpiece clock old 置き時計",
	"⌛": "hourglass done time 砂時計 時間",
	"⏳": "hourglass not done flowing 砂時計 進行中",
	"🚬": "cigarette smoking tobacco タバコ 喫煙",
	"⚰️": "coffin funeral death 棺 葬式",
	"🪦": "headstone grave cemetery 墓石 墓",
	"⚱️": "funeral urn ashes 骨壺",
	"🗿": "moai statue Easter Island モアイ 石像",
	"🪧": "placard sign protest プラカード 看板",
	"🪪": "identification card ID 身分証 IDカード",

	// ==================== SYMBOLS ====================
	"❤️": "red heart love passion 赤 ハート 愛 好き",
	"🧡": "orange heart warm affection オレンジ ハート",
	"💛": "yellow heart friendship happy 黄色 ハート 友情",
	"💚": "green heart nature health 緑 ハート 自然",
	"💙": "blue heart trust loyalty 青 ハート 信頼",
	"💜": "purple heart fashion style 紫 ハート",
	"🖤": "black heart dark goth 黒 ハート ダーク",
	"🤍": "white heart pure clean 白 ハート 純粋",
	"🤎": "brown heart warm earth 茶色 ハート",
	"🔴": "red circle dot 赤丸 赤い丸",
	"🟠": "orange circle dot オレンジ丸",
	"🟡": "yellow circle dot 黄色丸",
	"🟢": "green circle dot 緑丸",
	"🔵": "blue circle dot 青丸",
	"🟣": "purple circle dot 紫丸",
	"🟤": "brown circle dot 茶色丸",
	"⚫": "black circle dot 黒丸",
	"⚪": "white circle dot 白丸",
	"🟥": "red square 赤四角",
	"🟧": "orange square オレンジ四角",
	"🟨": "yellow square 黄色四角",
	"🟩": "green square 緑四角",
	"🟦": "blue square 青四角",
	"🟪": "purple square 紫四角",
	"🟫": "brown square 茶色四角",
	"⬛": "black large square 黒大四角",
	"⬜": "white large square 白大四角",
	"◼️": "black medium square 黒中四角",
	"◻️": "white medium square 白中四角",
	"◾": "black medium-small square 黒小四角",
	"◽": "white medium-small square 白小四角",
	"▪️": "black small square 黒極小四角",
	"▫️": "white small square 白極小四角",
	"🔶": "large orange diamond オレンジ ひし形 大",
	"🔷": "large blue diamond 青 ひし形 大",
	"🔸": "small orange diamond オレンジ ひし形 小",
	"🔹": "small blue diamond 青 ひし形 小",
	"🔺": "red triangle pointed up 赤三角 上",
	"🔻": "red triangle pointed down 赤三角 下",
	"💠": "diamond with dot 花形 ダイヤ",
	"🔘": "radio button circle 丸ボタン ラジオ",
	"🔳": "white square button 白四角ボタン",
	"🔲": "black square button 黒四角ボタン",
	"♈": "Aries zodiac ram 牡羊座 おひつじ",
	"♉": "Taurus zodiac bull 牡牛座 おうし",
	"♊": "Gemini zodiac twins 双子座 ふたご",
	"♋": "Cancer zodiac crab 蟹座 かに",
	"♌": "Leo zodiac lion 獅子座 しし",
	"♍": "Virgo zodiac maiden 乙女座 おとめ",
	"♎": "Libra zodiac scales 天秤座 てんびん",
	"♏": "Scorpio zodiac scorpion 蠍座 さそり",
	"♐": "Sagittarius zodiac archer 射手座 いて",
	"♑": "Capricorn zodiac goat 山羊座 やぎ",
	"♒": "Aquarius zodiac water bearer 水瓶座 みずがめ",
	"♓": "Pisces zodiac fish 魚座 うお",
	"⛎": "Ophiuchus zodiac serpent 蛇遣座 へびつかい",
	"🔀": "shuffle tracks random シャッフル ランダム",
	"🔁": "repeat all loop リピート 繰り返し",
	"🔂": "repeat single one リピートワン",
	"▶️": "play button start 再生 スタート",
	"⏩": "fast-forward next skip 早送り",
	"⏭️": "next track skip forward 次のトラック",
	"⏯️": "play or pause toggle 再生/一時停止",
	"◀️": "reverse play backward 逆再生",
	"⏪": "fast reverse rewind 巻き戻し",
	"⏮️": "previous track skip backward 前のトラック",
	"🔼": "upwards button triangle up 上向き 三角",
	"⏫": "fast up top 上へ 高速",
	"🔽": "downwards button triangle down 下向き 三角",
	"⏬": "fast down bottom 下へ 高速",
	"⏸️": "pause button stop 一時停止",
	"⏹️": "stop button halt 停止",
	"⏺️": "record button recording 録音 録画",
	"⏏️": "eject button disc イジェクト 取り出し",
	"🎦": "cinema movie theater 映画館 シネマ",
	"🔅": "dim button low brightness 暗い 明るさ低",
	"🔆": "bright button high brightness 明るい 明るさ高",
	"📶": "antenna bars signal strength 電波 アンテナ",
	"🛜": "wireless WiFi signal ワイヤレス WiFi 無線",
	"📳": "vibration mode phone バイブレーション 振動",
	"📴": "mobile phone off airplane mode 電源オフ 機内モード",
	"♀️": "female sign woman 女性 メス",
	"♂️": "male sign man 男性 オス",
	"⚧️": "transgender symbol トランスジェンダー",
	"✖️": "multiply cross math 掛ける バツ",
	"➕": "plus add math 足す プラス 追加",
	"➖": "minus subtract math 引く マイナス",
	"➗": "divide math division 割る 除算",
	"🟰": "heavy equals sign math 等号 イコール",
	"♾️": "infinity forever eternal 無限 永遠",
	"‼️": "double exclamation mark 二重感嘆符 ビックリ",
	"⁉️": "exclamation question mark 感嘆疑問符",
	"❓": "red question mark 疑問 はてな 赤",
	"❔": "white question mark 疑問 はてな 白",
	"❕": "white exclamation mark ビックリ 白",
	"❗": "red exclamation mark alert 感嘆符 ビックリ 赤",
	"💱": "currency exchange money 両替 通貨",
	"💲": "heavy dollar sign money ドル記号 お金",
	"⚕️": "medical symbol caduceus 医療 カドゥケウス",
	"♻️": "recycling symbol environment eco リサイクル 環境",
	"⚜️": "fleur-de-lis scout フルール・ド・リス ボーイスカウト",
	"🔱": "trident emblem poseidon 三叉の矛 トライデント",
	"📛": "name badge tag 名札 バッジ",
	"🔰": "Japanese symbol beginner wakaba 初心者 若葉マーク",
	"⭕": "hollow red circle correct right 丸 正解 マル",
	"✅": "check mark button done complete チェック 完了 OK",
	"☑️": "check box with check done チェックボックス 完了",
	"✔️": "check mark correct right チェック 正しい",
	"❌": "cross mark wrong incorrect バツ 間違い 不正解",
	"❎": "cross mark button wrong バツボタン",
	"➰": "curly loop 巻き ループ",
	"➿": "double curly loop 二重巻き",
	"〽️": "part alternation mark iorime 庵点",
	"✳️": "eight-spoked asterisk 米印",
	"✴️": "eight-pointed star 八芒星",
	"❇️": "sparkle shine bright キラキラ 輝き",
	"©️": "copyright symbol 著作権 コピーライト",
	"®️": "registered trademark 登録商標",
	"™️": "trade mark sign 商標 トレードマーク",
	"#️⃣": "keycap hash pound number ハッシュ シャープ",
	"*️⃣": "keycap asterisk star アスタリスク 星",
	"0️⃣": "keycap zero number 0 ゼロ",
	"1️⃣": "keycap one number 1 いち",
	"2️⃣": "keycap two number 2 に",
	"3️⃣": "keycap three number 3 さん",
	"4️⃣": "keycap four number 4 よん し",
	"5️⃣": "keycap five number 5 ご",
	"6️⃣": "keycap six number 6 ろく",
	"7️⃣": "keycap seven number 7 なな しち",
	"8️⃣": "keycap eight number 8 はち",
	"9️⃣": "keycap nine number 9 きゅう く",
	"🔟": "keycap ten number 10 じゅう",
	"🔠": "input Latin uppercase letters 大文字 ABC",
	"🔡": "input Latin lowercase letters 小文字 abc",
	"🔢": "input numbers 数字 123",
	"🔣": "input symbols 記号 入力",
	"🔤": "input Latin letters ABC アルファベット",
	"🅰️": "A button blood type A型",
	"🆎": "AB button blood type AB型",
	"🅱️": "B button blood type B型",
	"🆑": "CL button clear クリア",
	"🆒": "cool button slang クール かっこいい",
	"🆓": "free button gratis 無料 フリー",
	ℹ️: "information source help 情報 インフォメーション",
	"🆔": "ID button identification 身分証明 ID",
	"Ⓜ️": "circled M metro subway 丸M メトロ",
	"🆕": "new button fresh 新しい ニュー",
	"🆖": "NG button no good NG ダメ",
	"🅾️": "O button blood type O型",
	"🆗": "OK button good fine OK オッケー",
	"🅿️": "P button parking パーキング 駐車場",
	"🆘": "SOS button help emergency SOS 助けて",
	"🆙": "UP button up cool アップ 上",
	"🆚": "VS button versus versus 対 バーサス",
	"🈁": "Japanese here koko ここ",
	"🈂️": "Japanese service charge 有料",
	"🈷️": "Japanese monthly amount 月額",
	"🈶": "Japanese not free of charge 有",
	"🈯": "Japanese reserved 指 予約",
	"🉐": "Japanese bargain 得 お得",
	"🈹": "Japanese discount 割 割引",
	"🈚": "Japanese free of charge 無 無料",
	"🈲": "Japanese prohibited 禁 禁止",
	"🉑": "Japanese acceptable 可 可能",
	"🈸": "Japanese application 申 申請",
	"🈴": "Japanese passing grade 合 合格",
	"🈳": "Japanese vacancy 空 空き",
	"㊗️": "Japanese congratulations 祝 お祝い",
	"㊙️": "Japanese secret 秘 秘密",
	"🈺": "Japanese open for business 営 営業中",
	"🈵": "Japanese no vacancy 満 満席",
	"⬆️": "up arrow north 上矢印 北",
	"↗️": "upper right arrow northeast 右上矢印",
	"➡️": "right arrow east 右矢印 東",
	"↘️": "lower right arrow southeast 右下矢印",
	"⬇️": "down arrow south 下矢印 南",
	"↙️": "lower left arrow southwest 左下矢印",
	"⬅️": "left arrow west 左矢印 西",
	"↖️": "upper left arrow northwest 左上矢印",
	"↕️": "up-down arrow vertical 上下矢印 縦",
	"↔️": "left-right arrow horizontal 左右矢印 横",
	"↩️": "right arrow curving left return reply 戻る 返信",
	"↪️": "left arrow curving right forward 転送",
	"⤴️": "right arrow curving up 上カーブ矢印",
	"⤵️": "right arrow curving down 下カーブ矢印",
	"🔃": "clockwise vertical arrows reload 時計回り 更新",
	"🔄": "counterclockwise arrows refresh 反時計回り リフレッシュ",
	"🛐": "place of worship pray 礼拝所 祈り",
	"⚛️": "atom symbol science 原子 科学",
	"🕉️": "om Hindu sacred オーム ヒンドゥー",
	"✡️": "star of David Jewish ダビデの星 ユダヤ",
	"☸️": "wheel of dharma Buddhist 法輪 仏教",
	"☯️": "yin yang balance harmony 陰陽 バランス",
	"✝️": "Latin cross Christian 十字架 キリスト教",
	"☦️": "orthodox cross Christian 正教 十字架",
	"☪️": "star and crescent Islam 星と三日月 イスラム",
	"☮️": "peace symbol hippie 平和 ピース",
	"🕎": "menorah Jewish Hanukkah メノラー ハヌカ",
	"🔯": "six-pointed star dotted 六芒星",
	"⚠️": "warning sign caution danger 警告 注意 危険",
	"🚫": "prohibited forbidden ban 禁止 🚫",
	"🚳": "no bicycles prohibited 自転車禁止",
	"🚭": "no smoking prohibited 禁煙",
	"🚯": "no littering prohibited ポイ捨て禁止",
	"🚱": "non-potable water 飲料不可",
	"🚷": "no pedestrians prohibited 歩行者禁止",
	"📵": "no mobile phones prohibited 携帯禁止",
	"🔞": "no one under eighteen adult 18禁 成人",
	"☢️": "radioactive nuclear danger 放射能 核",
	"☣️": "biohazard danger バイオハザード 危険",
	"🏧": "ATM sign bank ATM 銀行",
	"🚮": "litter in bin sign trash ゴミ箱",
	"🚰": "potable water drinking 飲料水",
	"♿": "wheelchair accessible disability 車椅子 バリアフリー",
	"🚹": "men's room restroom 男性 トイレ",
	"🚺": "women's room restroom 女性 トイレ",
	"🚻": "restroom bathroom toilet トイレ お手洗い",
	"🚼": "baby symbol nursery 赤ちゃん ベビー",
	"🚾": "water closet WC bathroom WC トイレ",
	"🛂": "passport control immigration パスポート 入国審査",
	"🛃": "customs declaration 税関",
	"🛄": "baggage claim airport 手荷物 空港",
	"🛅": "left luggage storage 手荷物預かり",
	"🔥": "fire flame hot burn 炎 火 燃える 熱い",
	"⚡": "high voltage lightning bolt thunder 雷 稲妻 電撃",
	"💤": "zzz sleep snore 睡眠 寝る ZZZ",
	"🏁": "chequered flag finish race ゴール チェッカーフラッグ",
	"🚩": "triangular flag red flag warning 旗 赤旗",
	"🎌": "crossed flags Japan celebration 交差旗 日本",
	"🏳️": "white flag surrender peace 白旗 降参",
	"🏴": "black flag pirate 黒旗 海賊",
	"🏳️‍🌈": "rainbow flag pride LGBT レインボーフラッグ プライド",
	"🏳️‍⚧️": "transgender flag pride トランスジェンダーフラッグ",
	"🏴‍☠️": "pirate flag jolly roger 海賊旗 ドクロ",
};

export function searchEmojis(query: string): string[] {
	const q = query.toLowerCase();
	const results: string[] = [];
	for (const cat of EMOJI_CATEGORIES) {
		const labelMatch = cat.label.includes(q);
		for (const emoji of cat.emojis) {
			if (labelMatch || (EMOJI_KEYWORDS[emoji] ?? "").includes(q)) {
				results.push(emoji);
			}
		}
	}
	return results;
}
